### PR TITLE
[Do not Merge] For Uptest

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

#### Missing Dependencies in the Example Manifest:
- `examples/kinesis/streamconsumer.yaml`

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/wafregional/bytematchset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/streamconsumer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisvideo/stream.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/pinpoint/app.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/chime/voiceconnector.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/licensemanager/licenseconfiguration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ssm/patchbaseline.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/signer/signingprofile.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/servicecatalog/portfolio.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/lakeformation/resource.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/secretsmanager/secretpolicy.yaml"

**Comment by ulucinar** [comment]
`examples/kinesis/streamconsumer.yam` -> fails due to a missing dependency.

**Comment by ulucinar** [comment]
/test-examples="examples/kms/externalkey.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elastictranscoder/preset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/glue/userdefinedfunction.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/s3/bucketlifecycleconfiguration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appintegrations/eventintegration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/sesv2/configurationset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/emr/securityconfiguration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/configservice/configurationaggregator.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/networkmanager/globalnetwork.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/mediapackage/channel.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/medialive/multiplex.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/mediaconvert/queue.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/sns/topic.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/inspector2/enabler.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/fis/experimenttemplate.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ecrpublic/repositorypolicy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ds/directory.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/memorydb/acl.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/inspector/resourcegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/s3control/accountpublicaccessblock.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisanalyticsv2/applicationsnapshot.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/lexmodels/bot.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/deploy/app.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/location/tracker.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/opensearch/domain.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/route53recoveryreadiness/recoverygroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cognitoidp/resourceserver.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/accessanalyzer/analyzer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/lightsail/bucket.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/serverlessrepo/cloudformationstack.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elasticbeanstalk/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/neptune/parameter-group.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/transfer/server.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/scheduler/schedulegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/resourcegroups/group.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ecr/pullthroughcacherule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/dynamodb/contributorinsights.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/macie2/account.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/grafana/workspace.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ecs/taskdefinition.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudsearch/domain.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudwatchlogs/resourcepolicy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/route53resolver/rule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/workspaces/ipgroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/fsx/lustrefilesystem.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elb/attachment.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/codestarnotifications/notificationrule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/sqs/queue.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appmesh/mesh.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/iot/policy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/amplify/app.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudcontrol/resource.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/redshift/snapshotschedule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/gamelift/script.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudtrail/eventdatastore.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/evidently/project.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/applicationinsights/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/emrserverless/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/keyspaces/keyspace.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/iam/virtualmfadevice.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/networkfirewall/rulegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/mediastore/container.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloud9/environmentec2.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisanalytics/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/route53recoverycontrolconfig/cluster.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/redshiftserverless/redshiftserverlessnamespace.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/nodegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/apigatewayv2/vpclink.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/amp/workspace.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kafka/configuration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/batch/jobdefinition.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appsync/graphqlapi.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/dlm/lifecyclepolicy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/budgets/budget.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/servicediscovery/publicdnsnamespace.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/waf/bytematchset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ivs/recordingconfiguration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cur/reportdefinition.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/mq/configuration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appautoscaling/policy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/vpc/networkperformancemetricsubscription.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/codestarconnections/host.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/guardduty/detector.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/dax/parametergroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/docdb/globalcluster.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/firehose/deliverystream.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/dms/s3endpoint.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/globalaccelerator/listener.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ses/configurationset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/account/alternatecontact.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/autoscaling/launchconfiguration.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elbv2/lblistener.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/securityhub/standardssubscription.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/backup/framework.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudformation/stack.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/connect/instance.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elasticache/parametergroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ce/anomalymonitor.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/sfn/activity.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/devicefarm/project.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appstream/stack.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/rds/globalcluster.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/swf/domain.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cloudwatchevents/bus.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/datapipeline/pipeline.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/transcribe/vocabularyfilter.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elasticsearch/domain.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/codecommit/approvalruletemplateassociation.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/rolesanywhere/profile.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/xray/encryptionconfig.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ram/resourceshare.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/efs/backuppolicy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/dataexchange/dataset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/sagemaker/modelpackagegroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/athena/datacatalog.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/route53/record.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/transitgatewaymulticastdomainassociation.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/apprunner/autoscalingconfigurationversion.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/streamconsumer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/streamconsumer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/streamconsumer.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/batch/jobdefinition.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/amp/workspace.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudcontrol/resource.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisanalytics/application.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisanalyticsv2/applicationsnapshot.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/dynamodb/contributorinsights.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ecrpublic/repositorypolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ecrpublic/repositorypolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/efs/backuppolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elb/attachment.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ecrpublic/repositorypolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elb/attachment.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/eks/nodegroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elbv2/lblistener.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/eks/nodegroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/route.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisanalyticsv2/applicationsnapshot.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/route.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/route.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/appautoscaling/scheduledaction.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudformation/stackset.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/directconnect/hostedprivatevirtualinterface.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/amicopy.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/rds/instance.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/mainroutetableassociation.yaml"

**Comment by ulucinar** [comment]
Closing this draft PR as we've decided to continue on top of `v4.67.0`.

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/replicationgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/kinesisanalyticsv2/applicationsnapshot.yaml"

**Pull request closed without merging**
