### PR TITLE
added 1 resource for securityhub group

### LINKED ISSUE #212: Moving securityhub (1) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by kdibrov**
### Description of your changes

Fixes #212 
Moving 1 resources in the `securityhub` group:
- [x] [`aws_securityhub_invite_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_invite_accepter)

I have:
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manually and Uptest:
https://github.com/upbound/provider-aws/actions/runs/3733888127

### CODE REVIEW

**Comment by kdibrov** [comment]
/test-examples="examples/securityhub/inviteaccepter.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/securityhub/inviteaccepter.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/securityhub/inviteaccepter.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @kdibrov LGTM!

**Pull request merged**
