### PR TITLE
Adding aws_ec2_instance_state, aws_ec2_network_insights_analysis, aws_ec2_transit_gateway_policy_table, aws_evidently_feature, aws_evidently_project, aws_evidently_segment, aws_fis_experiment_template, aws_glue_schema to v1beta1 version

### LINKED ISSUE #494: Moving ec2(4), evidently(3), fis(1), fsx(1), glue(1) resources to v1beta1 version
* `ec2`
  * [x] [aws_ec2_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_instance_state)
  * [x] [aws_ec2_network_insights_analysis](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_analysis)
  * [x] [aws_ec2_transit_gateway_policy_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table)

* `evidently`
  * [x] [aws_evidently_feature](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_feature)
  * [x] [aws_evidently_project](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_project)
  * [x] [aws_evidently_segment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_segment)

* `fis`
  * [x] [aws_fis_experiment_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template)

* `glue`
  * [x] [aws_glue_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_schema)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Adding (8) resources:
* `ec2`
  * [x] [aws_ec2_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_instance_state)
  * [x] [aws_ec2_network_insights_analysis](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_analysis)
  * [x] [aws_ec2_transit_gateway_policy_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table)

* `evidently`
  * [x] [aws_evidently_feature](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_feature)
  * [x] [aws_evidently_project](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_project)
  * [x] [aws_evidently_segment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_segment)

* `fis`
  * [x] [aws_fis_experiment_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template)

* `glue`
  * [x] [aws_glue_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_schema)

Fixes #494 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual:
aws_ec2_instance_state - Instance resource refers to an AMI ID.
aws_ec2_instance_state

Manual & Uptest:
aws_ec2_network_insights_analysis - https://github.com/upbound/provider-aws/actions/runs/4243814905
aws_ec2_transit_gateway_policy_table - https://github.com/upbound/provider-aws/actions/runs/4243826171
aws_evidently_feature - https://github.com/upbound/provider-aws/actions/runs/4243828725
aws_evidently_project - Exists in the [aws_evidently_feature](https://github.com/upbound/provider-aws/actions/runs/4243828725) test
aws_evidently_segment - https://github.com/upbound/provider-aws/actions/runs/4243836389
aws_fis_experiment_template - https://github.com/upbound/provider-aws/actions/runs/4243840041
aws_glue_schema - https://github.com/upbound/provider-aws/actions/runs/4243842814

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/ec2/instancestate.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ec2/networkinsightsanalysis.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/evidently/feature.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/evidently/segment.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/fis/experimenttemplate.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/glue/schema.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
