### PR TITLE
Moving redshift(4) resources to v1beta1 version

### LINKED ISSUE #521: Moving redshift(4) resources to v1beta1 version
* `redshift`
  * [x] [aws_redshift_authentication_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_authentication_profile)
  * [x] [aws_redshift_hsm_client_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_hsm_client_certificate)
  * [x] [aws_redshift_hsm_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_hsm_configuration)
  * [x] [aws_redshift_usage_limit](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_usage_limit)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
* `redshift`
  * [x] [aws_redshift_authentication_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_authentication_profile)
  * [x] [aws_redshift_hsm_client_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_hsm_client_certificate)
  * [x] [aws_redshift_hsm_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_hsm_configuration)
  * [x] [aws_redshift_usage_limit](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_usage_limit)

Fixes #521 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual and Uptest:
`aws_redshift_authentication_profile ` - [Link](https://github.com/upbound/provider-aws/actions/runs/4204115447/jobs/7294357626)
`aws_redshift_hsm_client_certificate ` - [Link](https://github.com/upbound/provider-aws/actions/runs/4204119600/jobs/7294366076)
`aws_redshift_hsm_configuration ` - [Link](https://github.com/upbound/provider-aws/actions/runs/4204122476/jobs/7294372902)
`aws_redshift_usage_limit ` - [Link](https://github.com/upbound/provider-aws/actions/runs/4204126733/jobs/7294382484)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/redshift/authenticationprofile.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/redshift/hsmclientcertificate.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/redshift/hsmconfiguration.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/redshift/usagelimit.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @MyzaTaras

**Pull request merged**
