### PR TITLE
Configure route53recoverycontrolconfig group and add examples

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR configures resources in the route53recoverycontrolconfig group:

- [`aws_route53recoverycontrolconfig_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoverycontrolconfig_cluster)
- [`aws_route53recoverycontrolconfig_control_panel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoverycontrolconfig_control_panel)
- [`aws_route53recoverycontrolconfig_routing_control`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoverycontrolconfig_routing_control)
- [`aws_route53recoverycontrolconfig_safety_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoverycontrolconfig_safety_rule)

Fixes: https://github.com/upbound/provider-aws/issues/49

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- `aws_route53recoverycontrolconfig_cluster`, M, U(https://github.com/upbound/provider-aws/actions/runs/3782252088)
```shell
NAME                                                          READY   SYNCED   EXTERNAL-NAME
                                             AGE
cluster.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::569674547146:cl
uster/dfe979cd-3839-48ae-a72b-4c6a0198b691   102s
```
- `aws_route53recoverycontrolconfig_control_panel`, M, U(https://github.com/upbound/provider-aws/actions/runs/3782388426)
```shell
NAME                                                               READY   SYNCED   EXTERNAL-NAME
                                                   AGE
controlpanel.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::5696745471
46:controlpanel/a3831e82a1f9440d9849c163cb969585   3m21s

NAME                                                          READY   SYNCED   EXTERNAL-NAME
                                             AGE
cluster.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::569674547146:cl
uster/983b0d02-a184-45d5-a9ed-33acc57e2865   3m21s
```
- `aws_route53recoverycontrolconfig_routing_control`, M, U(https://github.com/upbound/provider-aws/actions/runs/3782324160)
```shell
NAME                                                          READY   SYNCED   EXTERNAL-NAME
                                             AGE
cluster.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::569674547146:cl
uster/9beb8057-85e9-4c9a-99cd-1657425c01fe   4m31s

NAME                                                                 READY   SYNCED   EXTERNAL-NAME
                                                                                     AGE
routingcontrol.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::56967454
7146:controlpanel/bea9faf471ac4f0cb836ca1445d45a49/routingcontrol/c1157b880e4045ba   4m31s
```
- `aws_route53recoverycontrolconfig_safety_rule`, M, U(https://github.com/upbound/provider-aws/actions/runs/3782453847)
```shell
NAME                                                               READY   SYNCED   EXTERNAL-NAME
                                                   AGE
controlpanel.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::5696745471
46:controlpanel/b7b0e9b26746458e8c0235975a6ccbe6   8m46s

NAME                                                          READY   SYNCED   EXTERNAL-NAME
                                             AGE
cluster.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::569674547146:cl
uster/65f148f5-23fe-44d6-9cb7-aabfb609a419   8m46s

NAME                                                             READY   SYNCED   EXTERNAL-NAME
                                                                             AGE
safetyrule.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::569674547146
:controlpanel/b7b0e9b26746458e8c0235975a6ccbe6/safetyrule/ed4b76e29df746a9   8m46s

NAME                                                                 READY   SYNCED   EXTERNAL-NAME
                                                                                     AGE
routingcontrol.route53recoverycontrolconfig.aws.upbound.io/example   True    True     arn:aws:route53-recovery-control::56967454
7146:controlpanel/b7b0e9b26746458e8c0235975a6ccbe6/routingcontrol/adea46779f654078   8m46s
```

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/route53recoverycontrolconfig/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/route53recoverycontrolconfig/routingcontrol.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/route53recoverycontrolconfig/controlpanel.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/route53recoverycontrolconfig/safetyrule.yaml"

**Comment by turkenf** [comment]
This PR is ready for review, thanks.

**Comment by turkenf** [comment]
This PR is ready for review, thanks.

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf LGTM!

**Pull request merged**
