### PR TITLE
Moving iot (11) resources to v1beta1 version

### LINKED ISSUE #44: Moving iot (11) resources to v1beta1 version
External name configuration of 11 resources in the `iot` group:

- [x] * [`aws_iot_certificate`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_certificate)
- [x] * [`aws_iot_indexing_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_indexing_configuration)
- [x] * [`aws_iot_logging_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_logging_options)
- [x] * [`aws_iot_policy_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_policy_attachment)
- [x] * [`aws_iot_provisioning_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_provisioning_template)
- [x] * [`aws_iot_role_alias`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_role_alias)
- [x] * [`aws_iot_thing_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_group)
- [x] * [`aws_iot_thing_group_membership`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_group_membership)
- [x] * [`aws_iot_thing_principal_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_principal_attachment)
- [x] * [`aws_iot_thing_type`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_type)
- [x] * [`aws_iot_topic_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule)

### PR DESCRIPTION
**Pull request by steperchuk**
### Description of your changes
Add new 11 resources in the `iot` group:

- [x] * [`aws_iot_certificate`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_certificate)
- [x] * [`aws_iot_indexing_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_indexing_configuration)
- [x] * [`aws_iot_logging_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_logging_options)
- [x] * [`aws_iot_policy_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_policy_attachment)
- [x] * [`aws_iot_provisioning_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_provisioning_template)
- [x] * [`aws_iot_role_alias`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_role_alias)
- [x] * [`aws_iot_thing_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_group)
- [x] * [`aws_iot_thing_group_membership`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_group_membership)
- [x] * [`aws_iot_thing_principal_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_principal_attachment)
- [x] * [`aws_iot_thing_type`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_thing_type)
- [x] * [`aws_iot_topic_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule)

Fixes #44

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually and Uptest
[aws_iot_certificate](https://github.com/upbound/provider-aws/actions/runs/3758544572/jobs/6387016414)
[aws_iot_indexing_configuration](https://github.com/upbound/provider-aws/actions/runs/3758546152/jobs/6387019594)
[aws_iot_logging_options](https://github.com/upbound/provider-aws/actions/runs/3758546966/jobs/6387020243)
[aws_iot_policy_attachment](https://github.com/upbound/provider-aws/actions/runs/3758547717/jobs/6387021775)
[aws_iot_provisioning_template](https://github.com/upbound/provider-aws/actions/runs/3758548518/jobs/6387023585)
[aws_iot_role_alias](https://github.com/upbound/provider-aws/actions/runs/3758549242/jobs/6387025592)
[aws_iot_thing_group](https://github.com/upbound/provider-aws/actions/runs/3758550729/jobs/6387028432)
[aws_iot_thing_group_membership](https://github.com/upbound/provider-aws/actions/runs/3758551591)
[aws_iot_thing_principal_attachment](https://github.com/upbound/provider-aws/actions/runs/3758552620/jobs/6387032420)
[aws_iot_thing_type](https://github.com/upbound/provider-aws/actions/runs/3758553379/jobs/6387033426)
[aws_iot_topic_rule](https://github.com/upbound/provider-aws/actions/runs/3758553898/jobs/6387035450)

### CODE REVIEW

**Comment by steperchuk** [comment]
/test-examples="examples/iot/certificate.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/indexingconfiguration.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/loggingoptions.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/policyattachment.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/provisioningtemplate.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/rolealias.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/thinggroup.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/thingprincipalattachment.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/thingtype.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/iot/topicrule.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @steperchuk LGTM!

**Pull request merged**
