### PR TITLE
Bump crossplane-runtime to commit 7fcb8c5cad6f

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

This PR bumps crossplane-runtime dependency to the commit `7fcb8c5cad6f` to consume https://github.com/crossplane/crossplane-runtime/pull/666. It also bumps upjet to `v1.2.0`.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta2/route.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/opensearchserverless/v1beta1/accesspolicy.yaml,examples/opensearchserverless/v1beta1/lifecyclepolicy.yaml,examples/opensearchserverless/v1beta1/securitypolicy.yaml,examples/opensearchserverless/v1beta1/securityconfig.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta2/route.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/opensearchserverless/v1beta1/accesspolicy.yaml,examples/opensearchserverless/v1beta1/lifecyclepolicy.yaml,examples/opensearchserverless/v1beta1/securitypolicy.yaml,examples/opensearchserverless/v1beta1/securityconfig.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Pull request merged**
