### PR TITLE
Moving s3(1), s3control(4), workspaces(2), xray(3) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes

Moving `s3` 1 resource to v1beta1 version
- [x] [aws_s3_object_copy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object_copy)

Moving `s3control` 4 resources to v1beta1 version
- [x] [aws_s3control_multi_region_access_point](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_multi_region_access_point)
- [x] [aws_s3control_multi_region_access_point_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_multi_region_access_point_policy)
- [x] [aws_s3control_object_lambda_access_point](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_object_lambda_access_point)
- [x] [aws_s3control_object_lambda_access_point_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_object_lambda_access_point_policy)

Moving `workspaces` 2 resources to v1beta1 version
- [x] [aws_workspaces_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_directory)
- [x] [aws_workspaces_ip_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_ip_group)

Moving `xray` 3 resources to v1beta1 version
- [x] [aws_xray_encryption_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_encryption_config)
- [x] [aws_xray_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_group)
- [x] [aws_xray_sampling_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_sampling_rule)

Fixes https://github.com/upbound/provider-aws/issues/413

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually:
[aws_s3control_multi_region_access_point_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_multi_region_access_point_policy) - Requires manual replacing {aws_s3control_multi_region_access_point.example.alias} - randomly generated alias could not to add automatically
Screenshot 2023-01-11 at 13 08 16

[aws_workspaces_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_directory) - Requires IAM role with name workspaces_DefaultRole to operate normally. We could not create role with name workspaces_DefaultRole automatically, this name is not meet regex.
Screenshot 2023-01-10 at 16 56 02

[aws_s3_object_copy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object_copy) - Requires public accessed destination_bucket_name and source_bucket_name with file file_name - we cant create file automatically.

Screenshot 2023-01-10 at 17 33 27

Uptasts:
Moving `s3control` 4 resources to v1beta1 version
- [x] [aws_s3control_multi_region_access_point](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_multi_region_access_point) - https://github.com/upbound/provider-aws/actions/runs/3892819456/jobs/6644684266
- [x] [aws_s3control_object_lambda_access_point](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_object_lambda_access_point) - https://github.com/upbound/provider-aws/actions/runs/3893043658/jobs/6645172692
- [x] [aws_s3control_object_lambda_access_point_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_object_lambda_access_point_policy) - https://github.com/upbound/provider-aws/actions/runs/3892821826/jobs/6644689058

Moving `workspaces` 2 resources to v1beta1 version
- [x] [aws_workspaces_ip_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_ip_group) - https://github.com/upbound/provider-aws/actions/runs/3892822640/jobs/6644691085

Moving `xray` 3 resources to v1beta1 version
- [x] [aws_xray_encryption_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_encryption_config) - https://github.com/upbound/provider-aws/actions/runs/3892823617/jobs/6644693438
- [x] [aws_xray_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_group) - https://github.com/upbound/provider-aws/actions/runs/3892824584/jobs/6644695453
- [x] [aws_xray_sampling_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_sampling_rule) - https://github.com/upbound/provider-aws/actions/runs/3892825590/jobs/6644697780

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/s3control/multiregionaccesspoint.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/objectlambdaaccesspoint.yamll"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/objectlambdaaccesspointpolicy.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/xray/encryptionconfig.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/xray/group.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/xray/samplingrule.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/objectlambdaaccesspoint.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @svscheg LGTM!

**Pull request merged**
