### PR TITLE
ec2: add aws_vpc_peering_connection_accepter, aws_vpc_peering_connection_options

### LINKED ISSUE #220: Moving EC2 (2) resources to v1beta1 version
Moving v1beta1 2 resources to the `ec2` group:
- [ ] [`aws_vpc_peering_connection_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection_accepter)
- [ ] [`aws_vpc_peering_connection_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection_options)

### PR DESCRIPTION
**Pull request by anastasiia-kvas**
### Description of your changes
Adding new resources from group ec2:
- [x] [`aws_vpc_peering_connection_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection_accepter)
- [x] [`aws_vpc_peering_connection_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_peering_connection_options)

Fixes #220 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_vpc_peering_connection_accepter` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3705710561/jobs/6279973735)
`aws_vpc_peering_connection_options` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3705711631/jobs/6279976698)

### CODE REVIEW

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/ec2/vpcpeeringconnectionoptions.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/ec2/vpcpeeringconnectionaccepter.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/ec2/vpcpeeringconnectionoptions.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @anastasiia-kvas LGTM!

**Pull request merged**
