### PR TITLE
Moving networkfirewall(1), networkmanager(4) resources to v1beta1 version

### LINKED ISSUE #543: Moving networkfirewall(1), networkmanager(4) resources to v1beta1 version
* `networkfirewall`
  * [x] [aws_networkfirewall_firewall](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall)

* `networkmanager`
  * [x] [aws_networkmanager_attachment_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_attachment_accepter)
  * [x] [aws_networkmanager_connect_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connect_attachment)
  * [x] [aws_networkmanager_core_network](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_core_network)
  * [x] [aws_networkmanager_vpc_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_vpc_attachment)

### PR DESCRIPTION
**Pull request by anastasiia-kvas**
### Description of your changes
Adding 5 resources to networkfirewall and networkmanager groups:

* `networkfirewall`
  * [x] [aws_networkfirewall_firewall](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall)

* `networkmanager`
  * [x] [aws_networkmanager_attachment_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_attachment_accepter)
  * [x] [aws_networkmanager_connect_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connect_attachment)
  * [x] [aws_networkmanager_core_network](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_core_network)
  * [x] [aws_networkmanager_vpc_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_vpc_attachment)

Fixes #543 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_networkfirewall_firewall` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4225499026)
`aws_networkmanager_attachment_accepter`- manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4225501072)
`aws_networkmanager_connect_attachment`- manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4225503244)
`aws_networkmanager_core_network`- manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4225506698)
`aws_networkmanager_vpc_attachment`- manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4225509187)

### CODE REVIEW

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/networkfirewall/firewall.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/networkmanager/attachmentaccepter.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/networkmanager/connectattachment.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/networkmanager/corenetwork.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/networkmanager/vpcattachment.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @anastasiia-kvas LGTM!

**Pull request merged**
