### PR TITLE
Moving kendra(5) resources to v1beta1 version

### LINKED ISSUE #522: Moving kendra(5) resources to v1beta1 version
* `kendra`
  * [x] [aws_kendra_data_source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source)
  * [x] [aws_kendra_experience](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_experience)
  * [x] [aws_kendra_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_index)
  * [x] [aws_kendra_query_suggestions_block_list](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_query_suggestions_block_list)
  * [x] [aws_kendra_thesaurus](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_thesaurus)

### PR DESCRIPTION
**Pull request by anastasiia-kvas**
### Description of your changes
Adding 5 resources in kendra group:

  * [x] [aws_kendra_data_source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source)
  * [x] [aws_kendra_experience](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_experience)
  * [x] [aws_kendra_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_index)
  * [x] [aws_kendra_query_suggestions_block_list](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_query_suggestions_block_list)
  * [x] [aws_kendra_thesaurus](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_thesaurus)

Fixes #522 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_kendra_data_source` - manual intervention
datasource
`aws_kendra_experience` - manual intervention
experience
`aws_kendra_index` - manual intervention
index
`aws_kendra_query_suggestions_block_list` - manual intervention
querysuggestionsblocklist
`aws_kendra_thesaurus` - manual intervention
thesaurus

### CODE REVIEW

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/datasource.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/datasource.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/datasource.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/experience.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/index.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/querysuggestionsblocklist.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/thesaurus.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/datasource.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/experience.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/index.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/querysuggestionsblocklist.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/kendra/thesaurus.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @anastasiia-kvas LGTM!

**Pull request merged**
