### PR TITLE
Moving elb (7) resources to v1beta1 version

### LINKED ISSUE #45: Moving elb (7) resources to v1beta1 version
External name configuration of 7 resources in the `elb` group:
* [`aws_app_cookie_stickiness_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/app_cookie_stickiness_policy)
* [`aws_lb_cookie_stickiness_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_cookie_stickiness_policy)
* [`aws_lb_ssl_negotiation_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_ssl_negotiation_policy)
* [`aws_load_balancer_backend_server_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/load_balancer_backend_server_policy)
* [`aws_load_balancer_listener_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/load_balancer_listener_policy)
* [`aws_load_balancer_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/load_balancer_policy)
* [`aws_proxy_protocol_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/proxy_protocol_policy)

Extracted from https://github.com/upbound/provider-aws/issues/63

### PR DESCRIPTION
**Pull request by steperchuk**
…_policy, aws_proxy_protocol_policy, aws_load_balancer_listener_policy, aws_lb_ssl_negotiation_policy, aws_load_balancer_backend_server_policy, aws_load_balancer_policy resources

### Description of your changes
Add new 7 resources in the `elb` group:
* [`aws_app_cookie_stickiness_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/app_cookie_stickiness_policy)
* [`aws_lb_cookie_stickiness_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_cookie_stickiness_policy)
* [`aws_lb_ssl_negotiation_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_ssl_negotiation_policy)
* [`aws_load_balancer_backend_server_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/load_balancer_backend_server_policy)
* [`aws_load_balancer_listener_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/load_balancer_listener_policy)
* [`aws_load_balancer_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/load_balancer_policy)
* [`aws_proxy_protocol_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/proxy_protocol_policy)

Fixes #45

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually as Depends on ELB with a manual intervention as it requires a certificate in Issued State 

**aws_lb_ssl_negotiation_policy**
aws_lb_ssl_negotiation_policy

**aws_load_balancer_backend_server_policy**
aws_load_balancer_backend_server_policy

**aws_load_balancer_listener_policy**
aws_load_balancer_listener_policy

**aws_load_balancer_policy**
aws_load_balancer_policy

Manually and Uptest
[aws_app_cookie_stickiness_policy](https://github.com/upbound/provider-aws/actions/runs/3765576054/jobs/6401203226)
[aws_lb_cookie_stickiness_policy](https://github.com/upbound/provider-aws/actions/runs/3765577042/jobs/6401204941)
[aws_proxy_protocol_policy](https://github.com/upbound/provider-aws/actions/runs/3765577868/jobs/6401206438)

### CODE REVIEW

**Comment by steperchuk** [comment]
/test-examples="examples/elb/appcookiestickinesspolicy.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/elb/lbcookiestickinesspolicy.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/elb/proxyprotocolpolicy.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @steperchuk LGTM!

**Pull request merged**
