### PR TITLE
[release-0.47] Bump upjet to 1.1.3

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

This PR bumps the upjet dependency to 1.1.2 for including [StateFunc fix](https://github.com/crossplane/upjet/pull/358).

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by sergenyalcin** [comment]
Because of the shared runner out-of-memory issues, for now, we ran the following jobs locally:

`check-diff` (locally passed) ✅
`unit-tests` (locally passed) ✅

Also, the uptest runs cover the local-deploy job. In other words, in uptest runs, we ensure that the packages are correctly deployed because the work done in `local-deploy` is done.

**Comment by ulucinar** [comment]
Looks like (at least) the `check-diff` job has failed to due to insufficient disk space. Let me open a PR which conditionally introduces the disk cleanup step and see if it helps here. I remember these were failing previously for this branch.

**Pull request merged**
