### PR TITLE
Consume upjet with custom metrics

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

This PR bumps the upjet dependency to make the new custom Prometheus metrics available in the provider's runtime. Please see https://github.com/upbound/upjet/pull/170 for the available metrics and examples.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Please see https://github.com/upbound/upjet/pull/170.

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by ulucinar** [comment]
Hi @turkenf,
We can use the package `ulucinar/provider-aws-amd64:d1ae6936` for testing upgrades from `v0.30.0`.

**Comment by turkenf** [comment]
Hi @ulucinar 
I completed the test with the given `ulucinar/provider-aws-amd64:d1ae6936` package. After creating a resource in v0.30.0, I changed the package. I edited the current resource and checked it successfully.
```
> kubectl get providerrevisions.pkg.crossplane.io
NAME                        HEALTHY   REVISION   IMAGE                                          STATE      DEP-FOUND   DEP-INSTALLED   AGE
provider-aws-2e7deee3c48d   True      2          ulucinar/provider-aws-amd64:d1ae6936           Active                                 12h
provider-aws-30b1a6158012   True      1          xpkg.upbound.io/upbound/provider-aws:v0.30.0   Inactive                               12h
```

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Pull request merged**
