### PR TITLE
added aws_wafregional_xss_match_set, aws_wafv2_ip_set, aws_wafv2_rege…

### LINKED ISSUE #421: Moving Wafregional(1), wafv2(3) resources to v1beta1 version
Moving `Wafregional ` 2 resources to v1beta1 version
- [x] [aws_wafregional_xss_match_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_xss_match_set)

Moving `wafv2` 3 resources to v1beta1 version
- [x] [aws_wafv2_ip_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_ip_set)
- [x] [aws_wafv2_regex_pattern_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_regex_pattern_set)
- [x] [aws_wafv2_rule_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group)

### PR DESCRIPTION
**Pull request by kdibrov**
### Description of your changes

Fixes #421 
Added aws_wafregional_xss_match_set, aws_wafv2_ip_set, aws_wafv2_regex_pattern_set, aws_wafv2_rule_group resources to wafregional and wafv2 groups

**wafregional**
- [x] [aws_wafregional_xss_match_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_xss_match_set)

**wafv2**
- [x] [aws_wafv2_ip_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_ip_set)
- [x] [aws_wafv2_regex_pattern_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_regex_pattern_set)
- [x] [aws_wafv2_rule_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group)

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manually and Uptest:
https://github.com/upbound/provider-aws/actions/runs/3806686372
https://github.com/upbound/provider-aws/actions/runs/3806684503
https://github.com/upbound/provider-aws/actions/runs/3806681695
https://github.com/upbound/provider-aws/actions/runs/3806675956

### CODE REVIEW

**Comment by kdibrov** [comment]
/test-examples="examples/wafregional/xssmatchset.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/wafv2/ipset.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/wafv2/regexpatternset.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/wafv2/rulegroup.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @kdibrov LGTM!

**Pull request merged**
