### PR TITLE
Moving directory_service(1), dms(1), dynamodb(1), efs(1), emrserverless(1) resources to v1beta1 version

### LINKED ISSUE #559: Moving directory_service(1), dms(1), dynamodb(1), efs(1), emrserverless(1) resources to v1beta1 version
* `directory_service`
  * [x] [aws_directory_service_shared_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory)

* `dms`
  * [x] [aws_dms_s3_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_s3_endpoint)

* `dynamodb`
  * [x] [aws_dynamodb_table_replica](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_replica)

* `efs`
  * [x] [aws_efs_replication_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_replication_configuration)

* `emrserverless`
  * [x] [aws_emrserverless_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrserverless_application)

### PR DESCRIPTION
**Pull request by anastasiia-kvas**
### Description of your changes
Adding 5 resources in groups:

* `directory_service`
  * [x] [aws_directory_service_shared_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory)

* `dms`
  * [x] [aws_dms_s3_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_s3_endpoint)

* `dynamodb`
  * [x] [aws_dynamodb_table_replica](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_replica)

* `efs`
  * [x] [aws_efs_replication_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_replication_configuration)

* `emrserverless`
  * [x] [aws_emrserverless_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrserverless_application)

Fixes #559 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_directory_service_shared_directory` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4565041279)
`aws_dms_s3_endpoint` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4565039093)
`aws_dynamodb_table_replica` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4566849706)
`aws_efs_replication_configuration` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4565047139)
`aws_emrserverless_application` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/4568105870)

### CODE REVIEW

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/dms/s3endpoint.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/ds/shareddirectory.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/dynamodb/tablereplica.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/efs/replicationconfiguration.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/emrserverless/application.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/efs/replicationconfiguration.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @anastasiia-kvas LGTM!

**Comment by turkenf** [comment]
Required status checks have been changed, could you please rebase this PR?

**Comment by svscheg** [comment]
/test-examples="examples/emrserverless/application.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/emrserverless/application.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/dynamodb/tablereplica.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/emrserverless/application.yaml"

**Pull request merged**
