### PR TITLE
elastictranscoder: add aws_elastictranscoder_preset, aws_elastictranscoder_pipeline

### LINKED ISSUE #292: Moving elastictranscoder (2) resources to v1beta1 version
Moving 2 resources in the elastictranscoder group:

- [ ]  [aws_elastictranscoder_preset](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastictranscoder_preset)
- [ ] [aws_elastictranscoder_pipeline](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastictranscoder_pipeline)

### PR DESCRIPTION
**Pull request by anastasiia-kvas**
### Description of your changes
Adding new resources from group elastictranscoder:
- [x]  [aws_elastictranscoder_preset](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastictranscoder_preset)
- [x] [aws_elastictranscoder_pipeline](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastictranscoder_pipeline)

Fixes #292 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`add aws_elastictranscoder_preset` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3733094038/jobs/6333433656)
`aws_elastictranscoder_pipeline` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3733190731)

### CODE REVIEW

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/elastictranscoder/pipeline.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/elastictranscoder/preset.yaml"

**Comment by anastasiia-kvas** [comment]
/test-examples="examples/elastictranscoder/pipeline.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @anastasiia-kvas LGTM!

**Pull request merged**
