### PR TITLE
CognitoIDP[UserPoolClient]: Avoid underlying provider validation failure

### LINKED ISSUE #752: provider-aws-cognitoidp:v0.36.0 User Pool Client Validation Error
### What happened?

When creating a Cognito user pool client, the following error message occurs:
```
observe failed: cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 validation error(s) found.
      - minimum field size of 1, DescribeUserPoolClientInput.ClientId.
```

The expected behavior is for the user pool client to be created without the error.

### How can we reproduce it?

You can reproduce the issue using the example at https://github.com/upbound/provider-aws/blob/main/examples/cognitoidp/userpooluicustomization.yaml.

You will see the following error.
```
    Message:               observe failed: cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DescribeUserPoolClientInput.ClientId.
```

### What environment did it happen in?

* Crossplane Version: 12.2
* Provider Version: provider-aws-cognitoidp:v0.36.0
* Kubernetes Version:  1.27 
* Kubernetes Distribution:  EKS

### PR DESCRIPTION
**Pull request by ytsarev**
### Description of your changes

* In a current state the instantiation of `UserPoolClient` fails with
  ```
  cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 
  validation error(s) found.
  - minimum field size of 1, DescribeUserPoolClientInput.ClientId.
  ```
  unless we explicitly set the `external-name` annotation. See #752 for more debugging data

* This change will preset the `id` with `spec.forProvider.name` to avoid the validation failure. The `id` will be populated eventually with the dynamic value from the cloud provider

* I also tried to follow the doc at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#import but it seems to be wrong in practice:

  If we use smth like

  ```
  TemplatedStringAsIdentifierWithNoName("{{ .parameters.user_pool_id }}/{{ .parameters.name }}"),
  ```

  it will fail with
  ```
  cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (us-west-1_dMnICLKVB/): InvalidParameterException: 1 validation error detected: Value 'us-west-1_dMnICLKVB/' at 'clientId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+]+
  ```

  It proves that the import doc deviates from reality and fails its own provider validation.

* It is possible that we observe the bug in the underlying terraform aws provider.

* This fix provides best possible solution without the fix of underlying provider and associated costs.

* Fixes #752

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

e2e with example from `examples/cognitoidp/userpooluicustomization.yaml`

I will also execute uptest separately below

### CODE REVIEW

**Comment by ytsarev** [comment]
/test-examples="examples/cognitoidp/userpooluicustomization.yaml"

**Comment by jeanduplessis** [comment]
@ytsarev please run make generate locally and push any diffs up in this PR

**Comment by ytsarev** [comment]
@jeanduplessis Thanks for the catch! I actually didn't expect that and don't like what the generator did, investigating further.

**Comment by ytsarev** [comment]
/test-examples="examples/cognitoidp/userpooluicustomization.yaml"

**Comment by ytsarev** [comment]
@jeanduplessis updated the solution with the function that does not change CRD structure/name field requirement.

**Review by jeanduplessis — APPROVED** [review]

**Pull request merged**
