### PR TITLE
Improve example manifests for rds group

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR fixes example manifests and makes them uptestable for the following resources in `rds` group:

- `Snapshot`
- `InstanceRoleAssociation`
- `ClusterRoleAssociation`
- `ClusterActivityStream`
- `ClusterEndpoint`
- `ClusterParameterGroup`
- `ClusterSnapshot`
- `DBInstanceAutomatedBackupsReplication`
- `DBSnapshotCopy`

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested with uptest in comments below.

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/rds/snapshot.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/clusterroleassociation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/dbsnapshotcopy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/dbinstanceautomatedbackupsreplication.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/clustersnapshot.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/clusterparametergroup.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/clusterendpoint.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/clusteractivitystream.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/clustersnapshot.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/rds/dbinstanceautomatedbackupsreplication.yaml"

**Review by ulucinar — APPROVED** [review]
Thanks @turkenf, great care for the quality of our example manifests. Very much appreciated.

**Pull request merged**
