### PR TITLE
Add examples with update parameter for secretsmanager secret

### PR DESCRIPTION
**Pull request by mbbush**
### Description of your changes

Adds tests which fail because of the bug #1128, which can be used to validate the fix in #1144

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by mbbush** [comment]
/test-examples="examples/secretsmanager/v1beta1/secret.yaml"
This should fail because #1128 hasn't been fixed yet in this branch.

**Comment by mbbush** [comment]
/test-examples="examples/secretsmanager/v1beta1/secret-withreplica.yaml"
This should fail because https://github.com/upbound/provider-aws/issues/1128 hasn't been fixed yet in this branch.

**Comment by erhancagirici** [comment]
> secret-withreplica.yaml This should fail because #1128 hasn't been fixed yet in this branch.

This is actually expected to pass (and it [passed](https://github.com/upbound/provider-aws/actions/runs/7910315999) ), because the bug is relevant only when `replica` is not specified in the resource config.

**Comment by erhancagirici** [comment]
@mbbush thanks so much for the contribution! as mentioned in https://github.com/upbound/provider-aws/pull/1144#issuecomment-1945670878 I cherry-picked your change to #1144, so we can close this and continue there

**Pull request closed without merging**
