### PR TITLE
Adding ssm (7) resources to v1beta1 version

### LINKED ISSUE #329: Moving ssm (7) resources to v1beta1 version
Moving 7 resources in the ssm group:
- [x] [aws_ssm_activation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_activation)
- [x] [aws_ssm_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association)
- [x] [aws_ssm_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_document)
- [x] [aws_ssm_maintenance_window](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window)
- [x] [aws_ssm_maintenance_window_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window_target)
- [x] [aws_ssm_patch_baseline](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_patch_baseline)
- [x] [aws_ssm_patch_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_patch_group)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Add 7 resources in the ssm group:
- [x] [aws_ssm_activation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_activation)
- [x] [aws_ssm_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association)
- [x] [aws_ssm_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_document)
- [x] [aws_ssm_maintenance_window](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window)
- [x] [aws_ssm_maintenance_window_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window_target)
- [x] [aws_ssm_patch_baseline](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_patch_baseline)
- [x] [aws_ssm_patch_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_patch_group)

Fixes #329 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_ssm_activation` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752395982
`aws_ssm_association` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752401945
`aws_ssm_document` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752406899
`aws_ssm_maintenance_window` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752414449
`aws_ssm_maintenance_window_target` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752421552
`aws_ssm_patch_baseline` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752431215
`aws_ssm_patch_group` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3752439815

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/activation.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/association.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/document.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/maintenancewindow.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/maintenancewindowtarget.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/patchbaseline.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/ssm/patchgroup.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
