### PR TITLE
Switch from the NoFork terminology to the TerraformPluginSDK terminology

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Depends on: https://github.com/crossplane/upjet/pull/338

This PR switches from the `NoFork` terminology for the Terraform plugin SDK v2 based resources to the `TerraformPluginSDK` terminology. This is motivated by the fact that upjet now has native support for the Terraform plugin framework resources.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Via the following uptest runs:
- https://github.com/upbound/provider-aws/actions/runs/7742079275
- https://github.com/upbound/provider-aws/actions/runs/7742081756
- https://github.com/upbound/provider-aws/actions/runs/7742077564
- https://github.com/upbound/provider-aws/actions/runs/7742075240
- https://github.com/upbound/provider-aws/actions/runs/7742102728
- https://github.com/upbound/provider-aws/actions/runs/7742089543
- https://github.com/upbound/provider-aws/actions/runs/7742091210
- https://github.com/upbound/provider-aws/actions/runs/7742086022

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta1/securitygroupegressrule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta1/securitygroupingressrule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cognitoidp/v1beta1/userpoolclient.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/simpledb/v1beta1/domain.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appconfig/v1beta1/environment.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elasticache/v1beta1/replicationgroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elasticache/v1beta1/replicationgroup-engineVersion.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/elasticache/v1beta1/replicationgroup.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appconfig/v1beta1/environment.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/simpledb/v1beta1/domain.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/cognitoidp/v1beta1/userpoolclient.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta1/securitygroupingressrule.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta1/securitygroupegressrule.yaml"

**Review by erhancagirici — APPROVED** [review]
Thanks for the PR @ulucinar ! LGTM

**Comment by ulucinar** [comment]
/test-examples="examples/simpledb/v1beta1/domain.yaml"

**Pull request merged**
