### PR TITLE
Bump upjet to v1.1.1

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

This PR bumps the upjet version to `v1.1.1` and crossplane-runtime to commit `7fcb8c5cad6f` to consume the latest fixes. It also addressed an update loop issue for the `Firewall.networkfirewall` resource. The example manifest of the `Firewall.networkfirewall` resource is extended with the following two parameters:
```yaml
    firewallPolicyChangeProtection: true
    subnetChangeProtection: true
```
We have also enabled the update tests on this resource.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Via the following uptest runs:
- `VPC.ec2` -> https://github.com/upbound/provider-aws/actions/runs/7930558294
- `Firewall.networkfirewall` (with update step) -> https://github.com/upbound/provider-aws/actions/runs/7930174691

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/networkfirewall/firewall.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

Because of the shared runner out-of-memory issues, for now, we ran the following jobs locally:
- `check-diff` (locally passed) :white_check_mark:
- `unit-tests` (locally passed) :white_check_mark:

Also, the uptest runs cover the `local-deploy` job. In other words, in uptest runs, we ensure that the packages are correctly deployed because the work done in `local-deploy` is done. `lint` failure is also a known issue because of memory issue.

**Pull request merged**
