### PR TITLE
Adding aws_vpc_endpoint_security_group_association to ec2/v1beta1

### LINKED ISSUE #455: Request for `aws_vpc_endpoint_security_group_association` resource
### What resource do you need?

Terraform Resource Name:

### PR DESCRIPTION
**Pull request by balu-ce**
### Description of your changes

- [x] Adding 1 resource in the ec2 group.

Fixes #455 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by ytsarev** [comment]
/test-examples="examples/ec2/vpcendpointsecuritygroupassociation.yaml"

**Comment by balu-ce** [comment]
@ytsarev . can you please approve for the workflow once.

**Comment by ytsarev** [comment]
/test-examples="examples/ec2/vpcendpointsecuritygroupassociation.yaml"

**Review by ytsarev — APPROVED** [review]
Looks great, uptest is also green. Thank you so much for your contribution.

**Pull request merged**
