### PR TITLE
Moving sagemaker (9) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Moving 9 resources in the sagemaker group:

- [x] [aws_sagemaker_app](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app)
- [x] [aws_sagemaker_device](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device)
- [x] [aws_sagemaker_device_fleet](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device_fleet)
- [x] [aws_sagemaker_endpoint_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_endpoint_configuration)
- [x] [aws_sagemaker_image_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_image_version)
- [x] [aws_sagemaker_model](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model)
- [x] [aws_sagemaker_model_package_group_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model_package_group_policy)
- [x] [aws_sagemaker_workforce](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workforce)
- [x] [aws_sagemaker_workteam](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workteam)

Fixes https://github.com/upbound/provider-aws/issues/321

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually:

It requires an image which can be create/deleted only using AWS CLI

- [x] [aws_sagemaker_model](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model)
Screenshot 2023-01-16 at 23 54 09

- [x] [aws_sagemaker_endpoint_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_endpoint_configuration)
Screenshot 2023-01-17 at 09 27 08

- [x] [aws_sagemaker_image_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_image_version)
Screenshot 2023-01-17 at 12 33 10

Uptest:
- [x] [aws_sagemaker_app](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app) - https://github.com/upbound/provider-aws/actions/runs/3943841429/jobs/6749139800
- [x] [aws_sagemaker_device](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device) - https://github.com/upbound/provider-aws/actions/runs/3942617221/jobs/6746479695
- [x] [aws_sagemaker_device_fleet](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device_fleet) - https://github.com/upbound/provider-aws/actions/runs/3942618485/jobs/6746482148
- [x] [aws_sagemaker_model_package_group_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model_package_group_policy) - https://github.com/upbound/provider-aws/actions/runs/3940690076/jobs/6742118036
- [x] [aws_sagemaker_workforce](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workforce) - https://github.com/upbound/provider-aws/actions/runs/3940691150/jobs/6742120583
- [x] [aws_sagemaker_workteam](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workteam) - https://github.com/upbound/provider-aws/actions/runs/3943722194/jobs/6748882164

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples-generated/sagemaker/app.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/device.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/devicefleet.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/modelpackagegrouppolicy.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/workforce.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/workteam.yaml"

**Comment by svscheg** [comment]
/test-examples="examples-generated/sagemaker/app.yaml"

**Comment by svscheg** [comment]
/test-examples="examples-generated/sagemaker/app.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/device.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/devicefleet.yaml"

**Comment by svscheg** [comment]
/test-examples="examples-generated/sagemaker/app.yaml"

**Comment by svscheg** [comment]
/test-examples="examples-generated/sagemaker/app.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/workteam.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/sagemaker/app.yaml"

**Comment by dverveiko** [comment]
LGTM. Thanks!

**Review by sergenyalcin — COMMENTED** [review]
Thanks @svscheg LGTM!

**Review by sergenyalcin — APPROVED** [review]

**Pull request merged**
