### PR TITLE
Remove `.parameters.region` references from external-name configuration template bodies

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR removes `.parameters.region` references from external-name configuration template bodies for the following resources:

- aws_prometheus_rule_group_namespace
- aws_cloudformation_stack
- aws_appflow_flow
- aws_networkmanager_transit_gateway_connect_peer_association
- aws_networkmanager_customer_gateway_association
- aws_evidently_segment

Fixes: https://github.com/upbound/provider-aws/issues/673

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- `aws_prometheus_rule_group_namespace`: Manually, Uptest(https://github.com/upbound/provider-aws/actions/runs/5003502943)
```
NAME                                         READY   SYNCED   EXTERNAL-NAME   AGE
rulegroupnamespace.amp.aws.upbound.io/demo   True    True     demo            6m16s
```
- `aws_cloudformation_stack`: Manually, Uptest(https://github.com/upbound/provider-aws/actions/runs/5003675082)
```
NAME                                          READY   SYNCED   EXTERNAL-NAME                          AGE
stack.cloudformation.aws.upbound.io/network   True    True     2fef01d0-f3e0-11ed-8066-0639a74e3abf   3m33s
```
- `aws_appflow_flow`: Manually
```
NAME                                  READY   SYNCED   EXTERNAL-NAME   AGE
flow.appflow.aws.upbound.io/example   True    True     example         7m25s

NAME                                                   READY   SYNCED   EXTERNAL-NAME                 AGE
bucket.s3.aws.upbound.io/example-destination-test926   True    True     example-destination-test926   7m27s
bucket.s3.aws.upbound.io/example-source-test927        True    True     example-source-test927        7m27s

NAME                                                 READY   SYNCED   EXTERNAL-NAME                 AGE
bucketpolicy.s3.aws.upbound.io/example-destination   True    True     example-destination-test926   7m27s
bucketpolicy.s3.aws.upbound.io/example-source        True    True     example-source-test927        7m27s

NAME                               READY   SYNCED   EXTERNAL-NAME   AGE
object.s3.aws.upbound.io/example   True    True     object_key      7m27s
```
- `aws_networkmanager_transit_gateway_connect_peer_association`: Manually
```
NAME                                                                         READY   SYNCED   EXTERNAL-NAME
                                                                                   AGE
transitgatewayconnectpeerassociation.networkmanager.aws.upbound.io/example   True    True     global-network-0e0963e1afb6e1df1,arn:aws:ec2:us-wes
t-2:569674547146:transit-gateway-connect-peer/tgw-connect-peer-01279e6e548906544   21m
```
- `aws_networkmanager_customer_gateway_association`: Uptest(https://github.com/upbound/provider-aws/actions/runs/5002477254)
- `aws_evidently_segment`: Uptest(https://github.com/upbound/provider-aws/actions/runs/5002689073)

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/appflow/flow.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/networkmanager/transitgatewayconnectpeerassociation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/networkmanager/customergatewayassociation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/evidently/segment.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/networkmanager/transitgatewayconnectpeerassociation.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/amp/workspace.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cloudformation/stack.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appflow/flow.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/appflow/flow.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf LGTM!

**Pull request merged**
