### PR TITLE
Add aws_msk_scram_secret_association

### LINKED ISSUE #43: Moving kafka (1) resources to v1beta1 version
External name configuration of 1 resource in the `kafka` group:
- [ ] [`aws_msk_scram_secret_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_scram_secret_association)

Extracted from https://github.com/upbound/provider-aws/issues/61

### PR DESCRIPTION
**Pull request by chlunde**
### Description of your changes
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_scram_secret_association

Fixes #43

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.
- [ ] TODO: create testable examples

### How has this code been tested

Created a kafka cluster

Created a few secrets with AmazonMSK_ name prefix, labeled them and attached using ScramSecretAssociation:

```yaml
apiVersion: kafka.aws.upbound.io/v1beta1
kind: ScramSecretAssociation
metadata:
  name: example3
spec:
  forProvider:
    clusterArnRef:
      name: example
    region: us-east-1
    secretArnListSelector:
      policy:
        resolve: Always
      matchLabels:
        foo: bar
```

One thing to note is that if you have multiple ScramSecretAssociation objects it
will not work properly, sometimes one will clear secrets from the other.

### CODE REVIEW

**Comment by ulucinar** [comment]
Hi @chlunde,
Thank you very much for working on the `kafka.ScramSecretAssociation` resource. While I see this is still a draft, I just wanted to thank you and remind you we are here to support if you need any help.

And one early comment is that our current convention is to copy the [generated example manifest](https://github.com/upbound/provider-aws/blob/a92897c57aab04849c93a3f1c9a45faad231d0bc/examples-generated/kafka/scramsecretassociation.yaml) under to the examples directory and trigger uptest on it to make sure it meets our `v1beta1` criteria. You can invoke uptest by leaving a PR comment with a content similar to the following:
```
/test-examples="examples/kafka/scramsecretassociation.yaml"
```

**Comment by ulucinar** [comment]
The funny thing is that my comment above already triggered uptest on a non-existent target :)

**Comment by jeanduplessis** [comment]
@chlunde are you still interested in pushing this PR forward?

**Comment by oscardalmau-r3** [comment]
Hi @chlunde @jeanduplessis @ulucinar, are there any plans to move forward with this PR? We would like to use crossplane to deploy MSK clusters with SASL authentication but without the secret association is not possible?

**Comment by jeanduplessis** [comment]
I'm closing this PR as there's been no activity. If you would like to continue with this PR feel free to open it again.

**Comment by chlunde** [comment]
@oscardalmau-r3 @jeanduplessis we're waiting on a change from AWS for serverless kafka so this is not a priority for me right now. Anyone else can pick it up if they like of course!

**Pull request closed without merging**
