### PR TITLE
Added 10 resources for sagemaker group

### LINKED ISSUE #363: Moving sagemaker (10) resources to v1beta1 version
- [x] [aws_sagemaker_app_image_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app_image_config)
- [x] [aws_sagemaker_code_repository](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_code_repository)
- [x] [aws_sagemaker_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain)
- [x] [aws_sagemaker_feature_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_feature_group)
- [x] [aws_sagemaker_model_package_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model_package_group)
- [x] [aws_sagemaker_notebook_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance)
- [x] [aws_sagemaker_notebook_instance_lifecycle_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance_lifecycle_configuration)
- [x] [aws_sagemaker_image](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_image)
- [x] [aws_sagemaker_studio_lifecycle_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_studio_lifecycle_config)
- [x] [aws_sagemaker_user_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_user_profile)

Split from #321

### PR DESCRIPTION
**Pull request by kdibrov**
### Description of your changes

Fixes #363 
Added 10 resources to Sagemaker group:
- [x] [aws_sagemaker_app_image_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app_image_config)
- [x] [aws_sagemaker_code_repository](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_code_repository)
- [x] [aws_sagemaker_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain)
- [x] [aws_sagemaker_feature_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_feature_group)
- [x] [aws_sagemaker_model_package_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model_package_group)
- [x] [aws_sagemaker_notebook_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance)
- [x] [aws_sagemaker_notebook_instance_lifecycle_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance_lifecycle_configuration)
- [x] [aws_sagemaker_image](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_image)
- [x] [aws_sagemaker_studio_lifecycle_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_studio_lifecycle_config)
- [x] [aws_sagemaker_user_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_user_profile)

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manually and Uptest:
https://github.com/upbound/provider-aws/actions/runs/3758360542
https://github.com/upbound/provider-aws/actions/runs/3758354807
https://github.com/upbound/provider-aws/actions/runs/3758365277
https://github.com/upbound/provider-aws/actions/runs/3758371786
https://github.com/upbound/provider-aws/actions/runs/3758364091
https://github.com/upbound/provider-aws/actions/runs/3758353074
https://github.com/upbound/provider-aws/actions/runs/3758358210
https://github.com/upbound/provider-aws/actions/runs/3758361965
https://github.com/upbound/provider-aws/actions/runs/3758356342
https://github.com/upbound/provider-aws/actions/runs/3758366930

### CODE REVIEW

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/appimageconfig.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/coderepository.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/featuregroup.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/image.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/modelpackagegroup.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/notebookinstance.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/notebookinstancelifecycleconfiguration.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/userprofile.yaml"

**Comment by kdibrov** [comment]
/test-examples="examples/sagemaker/studiolifecycleconfig.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @kdibrov LGTM!

**Pull request merged**
