### PR TITLE
Moving directconnect (4) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Moving directconnect (4) resources to v1beta1 version

- [x] [`aws_dx_bgp_peer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_bgp_peer)
- [x] [`aws_dx_gateway_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_gateway_association)
- [x] [`aws_dx_gateway_association_proposal`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_gateway_association_proposal)
- [x] [`aws_dx_private_virtual_interface`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_private_virtual_interface)

Fixes https://github.com/upbound/provider-aws/issues/224

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually
Uptest:
-[`aws_dx_bgp_peer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_bgp_peer) - https://github.com/upbound/provider-aws/actions/runs/3698458722/jobs/6264694829
-[`aws_dx_gateway_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_gateway_association) - https://github.com/upbound/provider-aws/actions/runs/3701879325/jobs/6271588102
-[`aws_dx_gateway_association_proposal`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_gateway_association_proposal) - https://github.com/upbound/provider-aws/actions/runs/3699088133/jobs/6266063889
-[`aws_dx_private_virtual_interface`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_private_virtual_interface) - https://github.com/upbound/provider-aws/actions/runs/3701884745/jobs/6271598182

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociation.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociationproposal.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/privatevirtualinterface.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociation.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociationproposal.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/bgppeer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/bgppeer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/bgppeer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/bgppeer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/bgppeer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociation.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociationproposal.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/privatevirtualinterface.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/privatevirtualinterface.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/gatewayassociation.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/directconnect/privatevirtualinterface.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @svscheg LGTM!

**Pull request merged**
