### PR TITLE
Bump Terraform CLI to v1.5.5

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Bumps the Terraform CLI to `v1.5.5` and consumes the Terraform CLI from https://github.com/upbound/terraform/releases.
I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Via uptest

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Review by turkenf — APPROVED** [review]
Thank you @ulucinar, LGTM.

**Comment by ulucinar** [comment]
Local builds on certain platforms (especially 32-bit platforms) will currently fail. I don't know how many provider developers are on 32-bit platforms. If needed, we will add the corresponding binaries under to https://github.com/upbound/terraform/releases.

**Pull request merged**
