### PR TITLE
[release-1.1] Bump upjet to 1.2.2

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

This PR bumps the upjet dependency to 1.2.1 for including https://github.com/crossplane/upjet/pull/358.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by sergenyalcin** [comment]
/test-examples="examples/iam/v1beta1/policy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/iam/v1beta1/policy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/iam/v1beta1/policy.yaml"

**Review by ulucinar — APPROVED** [review]
Thanks @sergenyalcin. Please see https://github.com/upbound/provider-aws/pull/1188 for the review.

**Pull request merged**
