### PR TITLE
Add ProviderConfig auth documentation

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Adds the auth group annotation to the crossplane.yaml.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Adds documentation and schema info for ProviderConfig auth.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Updates the up version to v0.16.0.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Built locally and inspected image contents.

### CODE REVIEW

**Comment by ulucinar** [comment]
Built `ulucinar/provider-aws:v0.33.0-rc.1.5.g720f19e4` from this PR and tried installing it. I'm hitting the same issue I previously encountered [here](https://github.com/upbound/provider-azuread/pull/46#issuecomment-1505296407). I'm using the following commands to build a package:
```
make build.all
docker tag $(docker load -i _output/xpkg/linux_arm64/provider-aws-v0.33.0-rc.1.5.g720f19e4.xpkg -q | awk -F: '{print $3}') ulucinar/provider-aws:v0.33.0-rc.1.5.g720f19e4
```

I gave this PR a try to see whether the auth.yaml reference fixes the issue but looks like it does not.

My previous investigations point to the introduction of the [`xpkg.encode`](https://github.com/upbound/up/blob/e0ed99047f02fb430b96f39ccf87d4b6dd3bff2c/internal/xpkg/build.go#L289) function. Previously, the `package.yaml` contents in the base OCI image layer were coming from the [`parser.PackageParser.Parse`](https://github.com/crossplane/crossplane-runtime/blob/d5661210733b2bf926281f231ea1db9e5be7bab9/pkg/parser/parser.go#L95) method, and looked like the following:
```yaml
...

---
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/provider-gcp
    meta.crossplane.io/description: |
      Upbound's official Crossplane provider to manage Google Cloud Platform (GCP)
      cloudplatform services in Kubernetes.
    meta.crossplane.io/readme: |
      Provider GCP is a Crossplane provider for [Google Cloud Platform
      (GCP)](https://cloud.google.com) developed and supported by Upbound.
      Available resources and their fields can be found in the [Upbound
      Marketplace](https://marketplace.upbound.io/providers/upbound/provider-gcp).
      If you encounter an issue please reach out on support@upbound.io email
      address. This is a subpackage for the cloudplatform API group.
    friendly-name.meta.crossplane.io: Provider GCP (cloudplatform)
...

---
```

Please note the `...` (three dots) used as a document separator. But when I used the `v0.16.0` version of `up` accidentally while working on an experimental build pipeline for breaking provider-gcp into smaller subpackages, the contents of the `package.yaml` became:
```yaml
---
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    friendly-name.meta.crossplane.io: Provider GCP (cloudplatform)
    meta.crossplane.io/description: |
      Upbound's official Crossplane provider to manage Google Cloud Platform (GCP)
      cloudplatform services in Kubernetes.
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/readme: |
      Provider GCP is a Crossplane provider for [Google Cloud Platform
      (GCP)](https://cloud.google.com) developed and supported by Upbound.
      Available resources and their fields can be found in the [Upbound
      Marketplace](https://marketplace.upbound.io/providers/upbound/provider-gcp).
      If you encounter an issue please reach out on support@upbound.io email
      address. This is a subpackage for the gcp API group.
    meta.crossplane.io/source: github.com/upbound/provider-gcp
  creationTimestamp: null
  name: provider-gcp-cloudplatform
spec:
  controller:
    image: ""
---
```
, and I could no longer install the package, getting errors similar to the following:
```
cannot apply provider package deployment: cannot create object: Deployment.apps \"provider-aws-1284847c5792\" is invalid: spec.template.spec.containers[0].image: Required value
```

I tried installing the package built with `up@v0.16.0` with uxp versions `v1.10.1-up.1` and `1.11.3-up.1`.

**Comment by ulucinar** [comment]
Another problem is the `local-deploy` job does not catch this. This might be related to the fact that we are populating the package cache for the Crossplane package manager but I'm not sure how this could happen if we are just extracting the built xpkg to populate the cache. I need to check the details there.

**Comment by jastang** [comment]
@ulucinar ah! i think we need to cut a patch release for `up`. 

See @muvaf 's fix for this issue [here](https://github.com/upbound/up/pull/324). I'll tag you for additional review

**Comment by jastang** [comment]
xref https://github.com/upbound/homebrew-tap/pull/31

**Comment by jastang** [comment]
> Hi @jastang, Thanks for the pointer. I've successfully verified a build of `up` from that PR. We are good to go after we bump the `up` dependency in this PR. I can also bump it once a new release is ready.

@ulucinar patch release `v0.16.1` is out :)

**Review by ulucinar — APPROVED** [review]
Thanks @hasheddan & @jastang, lgtm.

**Pull request merged**
