### PR TITLE
Moving accessanalyzer (1),account (1), amplify (4) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Moving accessanalyzer (1),account (1), amplify (4) resources to v1beta1 version.

Moving 1 resource in the `accessanalyzer` group:
- [`aws_accessanalyzer_analyzer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/accessanalyzer_analyzer)

Moving 1 resource in the `account` group:
- [`aws_account_alternate_contact`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/account_alternate_contact)

Moving 4 resources in the `amplify` group:
- [`aws_amplify_app`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app)
- [`aws_amplify_backend_environment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_backend_environment)
- [`aws_amplify_branch`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_branch)
- [`aws_amplify_webhook`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_webhook)

Fixes https://github.com/upbound/provider-aws/issues/71

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually and Uptest.
- [`aws_accessanalyzer_analyzer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/accessanalyzer_analyzer) - https://github.com/upbound/provider-aws/actions/runs/3522156683/jobs/5904803364
- [`aws_account_alternate_contact`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/account_alternate_contact) - https://github.com/upbound/provider-aws/actions/runs/3522158119/jobs/5904806470
- [`aws_amplify_app`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app) - https://github.com/upbound/provider-aws/actions/runs/3522162150/jobs/5904814752
- [`aws_amplify_backend_environment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_backend_environment) - https://github.com/upbound/provider-aws/actions/runs/3522164390/jobs/5904819662
- [`aws_amplify_branch`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_branch) - https://github.com/upbound/provider-aws/actions/runs/3522165753/jobs/5904822157
- [`aws_amplify_webhook`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_webhook) - https://github.com/upbound/provider-aws/actions/runs/3522166942/jobs/5904825079

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/accessanalyzer/analyzer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/account/alternatecontact.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/app.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/backendenvironment.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/branch.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/webhook.yaml"

**Review by turkenh — APPROVED** [review]
Looking great, thanks @svscheg!

Two requests before merge: 
1. Please rebase your PR on top of latest main. There is a conflict after getting a couple of PRs merged.
2. Could you add some more details on `How has this code been tested` section? Similar to https://github.com/upbound/provider-aws/pull/147

**Comment by svscheg** [comment]
/test-examples="examples/accessanalyzer/analyzer.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/account/alternatecontact.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/backendenvironment.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/branch.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/amplify/webhook.yaml"

**Pull request merged**
