### PR TITLE
Move autoscaling (4), autoscalingplans (1) resources to v1beta1 version

### LINKED ISSUE #174: Moving autoscaling (4), autoscalingplans (1) resources to v1beta1 version
Moving 5 resources in the `autoscaling` group:
-  [x] [`aws_autoscaling_lifecycle_hook`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_lifecycle_hook)
-  [x] [`aws_autoscaling_notification`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_notification)
-  [x] [`aws_autoscaling_schedule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_schedule)
-  [x] [`aws_autoscaling_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy)

Moving 1 resource in the `autoscalingplans` group:
-  [x] [`aws_autoscalingplans_scaling_plan`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscalingplans_scaling_plan)

### PR DESCRIPTION
**Pull request by steperchuk**
### Description of your changes
Adding new resources to the `autoscaling` group:
-  [x] [`aws_autoscaling_lifecycle_hook`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_lifecycle_hook)
-  [x] [`aws_autoscaling_notification`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_notification)
-  [x] [`aws_autoscaling_schedule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_schedule)
-  [x] [`aws_autoscaling_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy)

Adding new resource to the `autoscalingplans` group:
-  [x] [`aws_autoscalingplans_scaling_plan`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscalingplans_scaling_plan)

Fixes #174

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
**Manually:**

aws_autoscaling_lifecycle_hook - depends on AutoscalingGroup resource which depends on LaunchConfiguration resource which requires manual intervention  
 lifecyclehook

aws_autoscaling_notification - depends on AutoscalingGroup resource which depends on LaunchConfiguration resource which requires manual intervention  
notification

aws_autoscaling_schedule - depends on AutoscalingGroup resource which depends on LaunchConfiguration resource which requires manual intervention  
schedule

aws_autoscaling_policy - depends on AutoscalingGroup resource which depends on LaunchConfiguration resource which requires manual intervention  
policy

aws_autoscalingplans_scaling_plan - depends on AutoscalingGroup resource which depends on LaunchConfiguration resource which requires manual intervention  
scalingplan

### CODE REVIEW

**Comment by steperchuk** [comment]
/test-examples="examples/autoscaling/lifecyclehook.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/autoscaling/notification.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/autoscaling/policy.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/autoscaling/schedule.yaml"

**Comment by steperchuk** [comment]
> @steperchuk Thanks for the PR. The PR name is descriptive but for these PRs that move resource versions to v1beta1, we may have a naming convention like this:
> 
> Move `<api_group_name>` (`<resource_count>`) resources to v1beta1 version Move autoscaling (1), autoscalingplans (4) resources to v1beta1 version

PR name updated

**Review by sergenyalcin — APPROVED** [review]
LGTM! Thanks @steperchuk

**Pull request merged**
