### PR TITLE
Bump crossplane-runtime, upjet dependency to master and GMP promote to BETA

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

In this PR:
- Updated the feature flag to be true by default, and the hack `main.go.tmpl` to use the beta flag(Changes in @lsviben's relevant [PR](https://github.com/upbound/provider-aws/pull/906)): [Related commit](https://github.com/upbound/provider-aws/pull/918/commits/81480f10efb9f626c5d7f29ba79c84466e6eaa24)
- Bumped crossplane-runtime dependency to the master branch: [Related commit](https://github.com/upbound/provider-aws/pull/918/commits/f9d68b7f40ab386b075c6791dacd7d69ee06bfbe)
- Bumped upjet dependency to the main branch: [Related commit](https://github.com/upbound/provider-aws/pull/918/commits/c050139d0a664673a32b194e1895e9ab7e312c50)
- Fixed deprecated pointer issue: [Related commit](https://github.com/upbound/provider-aws/pull/918/commits/4ab136dd5d80b03d8e9d361427d2d9ac84d339f7)

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Uptest runs:
- `VPC.ec2`: https://github.com/upbound/provider-aws/actions/runs/6494295092
- `Bucket.s3`: https://github.com/upbound/provider-aws/actions/runs/6494296727

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/s3/bucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/eks/cluster.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/s3/bucket.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/s3/bucket.yaml"

**Review by ulucinar — APPROVED** [review]
Thanks @turkenf, lgtm.

**Pull request merged**
