### PR TITLE
Fix the update loop in Firewall.networkfirewall resource

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Related PR: https://github.com/upbound/uptest/pull/180

This PR fixes an update loop issue in the `Firewall.networkfirewall` resource and extends the example manifest for the that resource with the `firewallPolicyChangeProtection` & `subnetChangeProtection` parameters, and enables the update tests on it.

This PR also bumps uptest to `v0.11.1` to properly run the update test on the `Firewall.networkfirewall` resource.

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Via an uptest run with the update-test step: https://github.com/upbound/provider-aws/actions/runs/8065145812

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/networkfirewall/v1beta1/firewall.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/networkfirewall/v1beta1/firewall.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Comment by ulucinar** [comment]
A local run of `make lint` has succeeded. Merging the PR...

**Pull request merged**
