### PR TITLE
Bump Terraform provider plugin version to v4.51.0

### LINKED ISSUE #154: Upgrade underlying AWS terraform provider
### What problem are you facing?

The current Terraform provider is outdated.

### How could Official AWS Provider help solve your problem?
Upgrade to the latest Terraform provider for AWS to enable access to more resources and bug fixes

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Fixes #154 

Bumps Terraform provider version to `v4.51.0`. 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Uptests:
examples/ec2/vpc.yaml -> https://github.com/upbound/provider-aws/actions/runs/3832657844
examples/apigatewayv2/vpclink.yaml -> https://github.com/upbound/provider-aws/actions/runs/3833016081
examples/eks/addon.yaml -> https://github.com/upbound/provider-aws/actions/runs/3873285889

Manual tests for breaking API changes:
-  appmesh.aws.upbound.io_gatewayroutes.yaml
```shell
NAME                                 READY   SYNCED   EXTERNAL-NAME   AGE
mesh.appmesh.aws.upbound.io/simple   True    True     simple          6m15s

NAME                                          READY   SYNCED   EXTERNAL-NAME                          AGE
gatewayroute.appmesh.aws.upbound.io/example   True    True     17bf7831-895b-4702-9226-e0702969e7a6   6m15s

NAME                                            READY   SYNCED   EXTERNAL-NAME                          AGE
virtualgateway.appmesh.aws.upbound.io/example   True    True     57f83cb0-3494-4bf3-bf66-11e52406dc94   6m15s

NAME                                             READY   SYNCED   EXTERNAL-NAME                          AGE
virtualservice.appmesh.aws.upbound.io/servicea   True    True     36793cf8-dc6f-41d0-a9f4-3698fb787883   6m15s

NAME                                           READY   SYNCED   EXTERNAL-NAME                          AGE
virtualnode.appmesh.aws.upbound.io/serviceb1   True    True     77b9a057-8702-445b-aaf3-69eab736c630   6m15s
```

-  appstream.aws.upbound.io_stacks.yaml
```shell
NAME                                     READY   SYNCED   EXTERNAL-NAME            AGE
stack.appstream.aws.upbound.io/example   True    True     new-test-stack-example   4m45s
```

-  appsync.aws.upbound.io_functions.yaml
```shell
NAME                                        READY   SYNCED   EXTERNAL-NAME   AGE
datasource.appsync.aws.upbound.io/example   True    True     example         5m3s

NAME                                        READY   SYNCED   EXTERNAL-NAME                AGE
graphqlapi.appsync.aws.upbound.io/example   True    True     6vwuwx4tincfzdkbbq5a36mdya   5m3s

NAME                                      READY   SYNCED   EXTERNAL-NAME                                           AGE
function.appsync.aws.upbound.io/example   True    True     6vwuwx4tincfzdkbbq5a36mdya-flseslkr6raffhxu7f7aswah24   5m3s
```

-  budgets.aws.upbound.io_budgets.yaml
```shell
NAME                                    READY   SYNCED   EXTERNAL-NAME   AGE
budget.budgets.aws.upbound.io/example   True    True     example         2m42s
```

-  ec2.aws.upbound.io_customergateways.yaml
```shell
NAME                                      READY   SYNCED   EXTERNAL-NAME           AGE
customergateway.ec2.aws.upbound.io/main   True    True     cgw-033966c821fcd4b09   3m28s
```

-  ec2.aws.upbound.io_defaultvpcdhcpoptions.yaml
```shell
NAME                                               READY   SYNCED   EXTERNAL-NAME            AGE
defaultvpcdhcpoptions.ec2.aws.upbound.io/default   True    True     dopt-061876298b75fb0fb   4m13s
```

-  ec2.aws.upbound.io_flowlogs.yaml
```shell
NAME                                          READY   SYNCED   EXTERNAL-NAME   AGE
group.cloudwatchlogs.aws.upbound.io/example   True    True     example         15m

NAME                                 READY   SYNCED   EXTERNAL-NAME          AGE
flowlog.ec2.aws.upbound.io/example   True    True     fl-0871d701ee08fba14   15m

NAME                                READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True    True     vpc-09d4b66cb28afc167   15m

NAME                              READY   SYNCED   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/example   True    True     example         15m
```

-  ec2.aws.upbound.io_natgateways.yaml
```shell
NAME                                READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True    True     vpc-0a68f96e4b6629c83   44m

NAME                                    READY   SYNCED   EXTERNAL-NAME           AGE
natgateway.ec2.aws.upbound.io/example   True    True     nat-0a6a5b2efba8a3749   44m

NAME                                       READY   SYNCED   EXTERNAL-NAME              AGE
subnet.ec2.aws.upbound.io/sample-subnet1   True    True     subnet-09476fc2e36846cdf   44m
```

-  elasticsearch.aws.upbound.io_domains.yaml
```shell
NAME                                          READY   SYNCED   EXTERNAL-NAME   AGE
domain.elasticsearch.aws.upbound.io/example   True    True     example         17m
```

-  glue.aws.upbound.io_crawlers.yaml
```shell
NAME                                                            READY   SYNCED   EXTERNAL-NAME               AGE
catalogdatabase.glue.aws.upbound.io/aws-glue-catalog-database   True    True     aws-glue-catalog-database   6m48s

NAME                                  READY   SYNCED   EXTERNAL-NAME   AGE
crawler.glue.aws.upbound.io/example   True    True     example         6m49s

NAME                              READY   SYNCED   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/example   True    True     example         6m48s
```

-  opensearch.aws.upbound.io_domains.yaml
```shell
NAME                                       READY   SYNCED   EXTERNAL-NAME                                                  AGE
domain.opensearch.aws.upbound.io/example   True    True     arn:aws:es:us-west-1:569674547146:domain/example-domain-name   21m
```

-  resourcegroups.aws.upbound.io_groups.yaml
```shell
NAME                                          READY   SYNCED   EXTERNAL-NAME   AGE
group.resourcegroups.aws.upbound.io/example   True    True     example         3m30s
```

-  s3.aws.upbound.io_bucketobjectlockconfigurations.yaml
```
NAME                                          READY   SYNCED   EXTERNAL-NAME        AGE
bucket.s3.aws.upbound.io/bucket-op-e0hr7gfk   True    True     bucket-op-e0hr7gfk   2m32s

NAME                                                      READY   SYNCED   EXTERNAL-NAME   AGE
bucketaccelerateconfiguration.s3.aws.upbound.io/example   True    True                     2m32s
```

-  sagemaker.aws.upbound.io_endpointconfigurations.yaml
```shell
NAME                                              READY   SYNCED   EXTERNAL-NAME                        AGE
rolepolicyattachment.iam.aws.upbound.io/example   True    True     example-20230126093619158900000001   38m

NAME                              READY   SYNCED   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/example   True    True     example         38m

NAME                                     READY   SYNCED   EXTERNAL-NAME   AGE
model.sagemaker.aws.upbound.io/example   True    True     example         39m

NAME                                                READY   SYNCED   EXTERNAL-NAME   AGE
endpointconfiguration.sagemaker.aws.upbound.io/ec   True    True     ec              39m
```

-  secretsmanager.aws.upbound.io_secretrotations.yaml
```shell
NAME                                  READY   SYNCED   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/sample-role   True    True     sample-role     6m50s

NAME                                                    READY   SYNCED   EXTERNAL-NAME            AGE
function.lambda.aws.upbound.io/example-secretrotation   True    True     example-secretrotation   7m57s

NAME                                                      READY   SYNCED   EXTERNAL-NAME                      AGE
permission.lambda.aws.upbound.io/example-secretrotation   True    True     AllowExecutionFromSecretsManager   7m57s

NAME                                                          READY   SYNCED   EXTERNAL-NAME
                                    AGE
secret.secretsmanager.aws.upbound.io/example-secretrotation   True    True     arn:aws:secretsmanager:us-east-1:569674547146:sec
ret:example-secretrotation-QD9ZVa   7m58s

NAME                                                   READY   SYNCED   EXTERNAL-NAME
                             AGE
secretrotation.secretsmanager.aws.upbound.io/example   True    True     arn:aws:secretsmanager:us-east-1:569674547146:secret:exa
mple-secretrotation-QD9ZVa   7m58s
```

-  servicecatalog.aws.upbound.io_products.yaml
```shell
NAME                                            READY   SYNCED   EXTERNAL-NAME        AGE
product.servicecatalog.aws.upbound.io/example   True    True     prod-kjfqkbv3m5keu   2m39s
```

-  ssm.aws.upbound.io_parameters.yaml
```shell
NAME                               READY   SYNCED   EXTERNAL-NAME   AGE
parameter.ssm.aws.upbound.io/foo   True    True     foo             2m6s
```

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/s3/bucket.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="elasticache/cluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="cloudfront/cachepolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="elasticache/subnetgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="cloudfront/originaccessidentity.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="eks/cluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="rds/clusterparametergroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="cloudfront/distribution.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="eks/fargateprofile.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="efs/filesystem.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="rds/globalcluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="docdb/globalcluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="dynamodb/globaltable.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="route53/zone.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="kms/key.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="ec2/launchtemplate.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="efs/mounttarget.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="sqs/queue.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="elasticache/replicationgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="ecr/repository.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/cluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/cachepolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/subnetgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/originaccessidentity.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/eks/cluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/rds/clusterparametergroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/distribution.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/eks/fargateprofile.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/efs/filesystem.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/rds/globalcluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/docdb/globalcluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/dynamodb/globaltable.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/route53/zone.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/kms/key.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/launchtemplate.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/efs/mounttarget.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/sqs/queue.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/replicationgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ecr/repository.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/responseheaderspolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/secretsmanager/secret.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/transfer/server.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/sns/topic.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/dynamodb/table.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/apigateway2/vpclink.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/eks/addon.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/s3/bucket.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/cluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/cachepolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/subnetgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/originaccessidentity.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/eks/cluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/rds/clusterparametergroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/distribution.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/efs/filesystem.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/rds/globalcluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/docdb/globalcluster.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/dynamodb/globaltable.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/route53/zone.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/kms/key.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/launchtemplate.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/efs/mounttarget.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/sqs/queue.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/replicationgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ecr/repository.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/cloudfront/responseheaderspolicy.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/secretsmanager/secret.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/transfer/server.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/sns/topic.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/dynamodb/table.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/vpc.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/apigatewayv2/vpclink.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/eks/fargateprofile.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/dynamodb/globaltable.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/replicationgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/replicationgroup.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks for all efforts @ulucinar @turkenf LGTM!

**Review by turkenf — APPROVED** [review]
Thanks @ulucinar @sergenyalcin

**Comment by ulucinar** [comment]
Thank you @sergenyalcin & @turkenf.

**Pull request merged**
