### PR TITLE
Configure elasticsearch(2) group examples

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR configures resources in the elasticsearch group:

- [`aws_elasticsearch_domain_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain_policy)
- [`aws_elasticsearch_domain_saml_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain_saml_options)

Fixes: https://github.com/upbound/provider-aws/issues/64

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
- `aws_elasticsearch_domain_policy`, M, U(https://github.com/upbound/provider-aws/actions/runs/4204409235)
```shell
NAME                                                       READY   SYNCED   EXTERNAL-NAME          AGE
domain.elasticsearch.aws.upbound.io/example-domainpolicy   True    True     example-domainpolicy   20m

NAME                                             READY   SYNCED   EXTERNAL-NAME                     AGE
domainpolicy.elasticsearch.aws.upbound.io/main   True    True     esd-policy-example-domainpolicy   20m
```
- `aws_elasticsearch_domain_saml_options`, M
```shell
NAME                                                            READY   SYNCED   EXTERNAL-NAME               AGE
domain.elasticsearch.aws.upbound.io/example-domainsamloptions   True    True     example-domainsamloptions   52m

NAME                                                                       READY   SYNCED   EXTERNAL-NAME               AGE
domainsamloptions.elasticsearch.aws.upbound.io/example-domainsamloptions   True    True     example-domainsamloptions   3m41s
```

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/elasticsearch/domainpolicy.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticsearch/domainsamloptions.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elasticsearch/domainsamloptions.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf LGTM!

**Pull request merged**
