### PR TITLE
Moving location(5) resources to v1beta1 version

### LINKED ISSUE #498: Moving location(5) resources to v1beta1 version
* `location`
  * [x] [aws_location_geofence_collection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_geofence_collection)
  * [x] [aws_location_place_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_place_index)
  * [x] [aws_location_route_calculator](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_route_calculator)
  * [x] [aws_location_tracker](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_tracker)
  * [x] [aws_location_tracker_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_tracker_association)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
* `location`
  * [x] [aws_location_geofence_collection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_geofence_collection)
  * [x] [aws_location_place_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_place_index)
  * [x] [aws_location_route_calculator](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_route_calculator)
  * [x] [aws_location_tracker](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_tracker)
  * [x] [aws_location_tracker_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_tracker_association)

Fixes #498 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual and Uptest
`aws_location_geofence_collection` - [Link](https://github.com/upbound/provider-aws/actions/runs/4144268508/jobs/7167118575)
`aws_location_place_index` - [Link](https://github.com/upbound/provider-aws/actions/runs/4144272822/jobs/7167125591)
`aws_location_route_calculator` - [Link](https://github.com/upbound/provider-aws/actions/runs/4144276155/jobs/7167133612)
`aws_location_tracker` - [Link](https://github.com/upbound/provider-aws/actions/runs/4144278989/jobs/7167141558)
`aws_location_tracker_association` - [Link](https://github.com/upbound/provider-aws/actions/runs/4144731896/jobs/7168159678)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/lakeformation/lftag.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/location/geofencecollection.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/location/placeindex.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/location/routecalculator.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/location/tracker.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/location/trackerassociation.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/location/trackerassociation.yaml"

**Review by turkenf — APPROVED** [review]
Thanks @MyzaTaras

**Pull request merged**
