### PR TITLE
Moving guardduty (3) resources to v1beta1 version

### LINKED ISSUE #40: Moving guardduty (3) resources to v1beta1 version
External name configuration of 9 resources in the `guardduty` group:
- [x] [`aws_guardduty_detector`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector)
- [x] [`aws_guardduty_filter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_filter)
- [x] [`aws_guardduty_member`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_member)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
Adding new resources from group guardduty
- [x] [`aws_guardduty_detector`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector)
- [x] [`aws_guardduty_filter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_filter)
- [x] [`aws_guardduty_member`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_member)

Fixes #40 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_guardduty_detector` - Manually and [Uptest](https://github.com/upbound/provider-aws/actions/runs/3806260242/jobs/6474906767)
`aws_guardduty_filter` - Manually and [Uptest](https://github.com/upbound/provider-aws/actions/runs/3806261824/jobs/6474908101)
`aws_guardduty_member` - Manually and [Uptest](https://github.com/upbound/provider-aws/actions/runs/3806399135/jobs/6475162861)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/detector.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/filter.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/filter.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/guardduty/detector.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/guardduty/filter.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/detector.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/filter.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/member.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/member.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/guardduty/member.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Pull request merged**
