### PR TITLE
PR#1161 test

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Because we cannot push to the feature branch of #1161, we will run the validation uptests on this PR and if everthing is green, we can leave the pointers in #1161 and merge it.

This PR's feature branch is the rebased version of #1161.

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by sergenyalcin** [comment]
/test-examples="examples/networkfirewall/firewall.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/elasticache/replicationgroup.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/secretsmanager/secret-withreplica.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/secretsmanager/secret.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/securitygroupegressrule.yaml"

**Comment by ulucinar** [comment]
We have successfully merged #1161.

**Comment by mbbush** [comment]
Thanks!

This makes me want to stop using the fork in my employer's org for pull requests, and instead use one in my account, so I can enable "allow maintainers to push to this branch", which isn't an option if the source fork is in a different GitHub org than the base.

**Pull request closed without merging**
