### PR TITLE
Fix for issue 505

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Fix for issue 505

1. Change "aws_ses_domain_identity": config.config.IdentifierFromProvider, to "aws_ses_domain_identity": config.ParameterAsIdentifier("domain"),
2. Add to the aws_ses_domain_identity and aws_ses_domain_dkim crossplane.io/external-name value

Fixes https://github.com/upbound/provider-aws/issues/505

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually

### CODE REVIEW

**Comment by sergenyalcin** [comment]
I think this PR can be fix https://github.com/upbound/provider-aws/issues/505. In theory, `domain` is an optional field and we will not have a breaking change here. However, we will have a behavioral change. I would prefer to switch `aws_ses_domain_dkim": config.IdentifierFromProvider` instead of changing the `aws_ses_domain_identity` configuration.

I want to also hear @ulucinar's idea on this.

**Comment by turkenf** [comment]
/test-examples="examples/ses/domainidentity.yaml"

**Comment by turkenh** [comment]
> I think this PR can be fix #505. In theory, `domain` is an optional field and we will not have a breaking change here. However, we will have a behavioral change. I would prefer to switch `aws_ses_domain_dkim": config.IdentifierFromProvider` instead of changing the `aws_ses_domain_identity` configuration.
> 
> I want to also hear @ulucinar's idea on this.

Just left a comment on the issue regarding this: https://github.com/upbound/provider-aws/issues/505#issuecomment-1582408170

@svscheg I believe we should make sure that this is not a breaking change by:

1. Install the existing provider version.
2. Create a `DomainIdentity` resource and make sure it is ready & synced.
3. Upgrade to a provider built from this PR (see https://github.com/crossplane/crossplane/discussions/3817)
4. Make sure provider is upgraded successfully.
5. Make sure the `DomainIdentity` resource stays `ready & synced` without any issues.

**Comment by turkenh** [comment]
@svscheg could you also remove the `Draft` in the title once this PR is ready for review/merge.

**Comment by turkenh** [comment]
> @turkenh I couldn't test with the method you suggested above. (I couldn’t build provider package from this PR, procedure [here](https://github.com/crossplane/crossplane/discussions/3817) didn’t work.)

Thanks @turkenf for testing. The procedure you followed already covers potential problems but it would still be valuable to see the package upgrade works properly. Could you retest with the RC image published after merging this PR?

**Review by turkenh — APPROVED** [review]

**Pull request merged**
