### PR TITLE
Moving waf(11), wafregional(10) resources to v1beta1 version

### LINKED ISSUE #376: Moving waf(11), wafregional(10) resources to v1beta1 version
Moving `waf` (11) resources to v1beta1 version
- [x] [`aws_waf_byte_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_byte_match_set)
- [x] [`aws_waf_geo_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_geo_match_set)
- [x] [`aws_waf_ipset`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_ipset)
- [x] [`aws_waf_rate_based_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_rate_based_rule)
- [x] [`aws_waf_regex_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_regex_match_set)
- [x] [`aws_waf_regex_pattern_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_regex_pattern_set)
- [x] [`aws_waf_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_rule)
- [x] [`aws_waf_size_constraint_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_size_constraint_set)
- [x] [`aws_waf_sql_injection_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_sql_injection_match_set)
- [x] [`aws_waf_web_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_web_acl)
- [x] [`aws_waf_xss_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_xss_match_set)

Moving `wafregional` (10) resources to v1beta1 version
- [x] [`aws_wafregional_byte_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_byte_match_set)
- [x] [`aws_wafregional_geo_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_geo_match_set)
- [x] [`aws_wafregional_ipset`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_ipset)
- [x] [`aws_wafregional_rate_based_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_rate_based_rule)
- [x] [`aws_wafregional_regex_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_regex_match_set)
- [x] [`aws_wafregional_regex_pattern_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_regex_pattern_set)
- [x] [`aws_wafregional_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_rule)
- [x] [`aws_wafregional_size_constraint_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_size_constraint_set)
- [x] [`aws_wafregional_sql_injection_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_sql_injection_match_set)
- [x] [`aws_wafregional_web_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_web_acl)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
Adding new resources from waf and wafregional:
waf
- [x] [`aws_waf_byte_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_byte_match_set)
- [x] [`aws_waf_geo_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_geo_match_set)
- [x] [`aws_waf_ipset`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_ipset)
- [x] [`aws_waf_rate_based_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_rate_based_rule)
- [x] [`aws_waf_regex_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_regex_match_set)
- [x] [`aws_waf_regex_pattern_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_regex_pattern_set)
- [x] [`aws_waf_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_rule)
- [x] [`aws_waf_size_constraint_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_size_constraint_set)
- [x] [`aws_waf_sql_injection_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_sql_injection_match_set)
- [x] [`aws_waf_web_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_web_acl)
- [x] [`aws_waf_xss_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_xss_match_set)

wafregional
- [x] [`aws_wafregional_byte_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_byte_match_set)
- [x] [`aws_wafregional_geo_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_geo_match_set)
- [x] [`aws_wafregional_ipset`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_ipset)
- [x] [`aws_wafregional_rate_based_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_rate_based_rule)
- [x] [`aws_wafregional_regex_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_regex_match_set)
- [x] [`aws_wafregional_regex_pattern_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_regex_pattern_set)
- [x] [`aws_wafregional_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_rule)
- [x] [`aws_wafregional_size_constraint_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_size_constraint_set)
- [x] [`aws_wafregional_sql_injection_match_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_sql_injection_match_set)
- [x] [`aws_wafregional_web_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafregional_web_acl)

Fixes #376 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_waf_byte_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795412155/jobs/6454508503)
`aws_waf_geo_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795566679/jobs/6454812087)
`aws_waf_ipset` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795630726/jobs/6454937683)
`aws_waf_rate_based_rule` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795707452/jobs/6455094118)
`aws_waf_regex_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795901874/jobs/6455480009)
`aws_waf_regex_pattern_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795724553/jobs/6455132347)
`aws_waf_rule` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3795906110/jobs/6455488789)
`aws_waf_size_constraint_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799245885/jobs/6461595000)
`aws_waf_sql_injection_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799259491/jobs/6461618801)
`aws_waf_web_acl` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799269374/jobs/6461637142)
`aws_waf_xss_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799304094/jobs/6461702863)

`aws_wafregional_byte_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799384650/jobs/6461858249)
`aws_wafregional_geo_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799398607/jobs/6461886390)
`aws_wafregional_ipset` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799407315/jobs/6461901992)
`aws_wafregional_rate_based_rule` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799415586/jobs/6461919141)
`aws_wafregional_regex_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799423743/jobs/6461935327)
`aws_wafregional_regex_pattern_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799431916/jobs/6461952059)
`aws_wafregional_rule` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799778665/jobs/6462626593)
`aws_wafregional_size_constraint_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799777265/jobs/6462626310)
`aws_wafregional_sql_injection_match_set` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799628582/jobs/6462329722)
`aws_wafregional_web_acl` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3799637826/jobs/6462348406)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/bytematchset.yaml”

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/bytematchset.yaml”

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/bytematchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/bytematchset.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/waf/bytematchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/geomatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/ipset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/ratebasedrule.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/regexmathset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/regexpatternset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/regexmatсhset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/regexmatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/rule.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples-generated/waf/regexmatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/sizeconstraintset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/sqlinjectionmatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/webacl.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/waf/xssmatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/bytematchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/geomatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/ipset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/ratebasedrule.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/regexmatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/regexpatternset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/rule.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/sizeconstraintset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/sqlinjectionmatchset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/webacl.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/rule.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/sizeconstraintset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/sizeconstraintset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/wafregional/rule.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Pull request merged**
