### PR TITLE
Moving sesv2(6) resources to v1beta1 version

### LINKED ISSUE #534: Moving sesv2(6) resources to v1beta1 version
* `sesv2`
  * [x] [aws_sesv2_configuration_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set)
  * [x] [aws_sesv2_configuration_set_event_destination](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set_event_destination)
  * [x] [aws_sesv2_dedicated_ip_pool](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_dedicated_ip_pool)
  * [x] [aws_sesv2_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity)
  * [x] [aws_sesv2_email_identity_feedback_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity_feedback_attributes)
  * [x] [aws_sesv2_email_identity_mail_from_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity_mail_from_attributes)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
* `sesv2`
  * [x] [aws_sesv2_configuration_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set)
  * [x] [aws_sesv2_configuration_set_event_destination](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set_event_destination)
  * [x] [aws_sesv2_dedicated_ip_pool](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_dedicated_ip_pool)
  * [x] [aws_sesv2_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity)
  * [x] [aws_sesv2_email_identity_feedback_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity_feedback_attributes)
  * [x] [aws_sesv2_email_identity_mail_from_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity_mail_from_attributes)

Fixes #534 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
aws_sesv2_configuration_set - [Link](https://github.com/upbound/provider-aws/actions/runs/4221825833/jobs/7329588502)
aws_sesv2_configuration_set_event_destination - [Link](https://github.com/upbound/provider-aws/actions/runs/4221829503/jobs/7329596854)
aws_sesv2_dedicated_ip_pool - [Link](https://github.com/upbound/provider-aws/actions/runs/4221834190/jobs/7329605971)
aws_sesv2_email_identity - [Link](https://github.com/upbound/provider-aws/actions/runs/4221837590/jobs/7329613303)
aws_sesv2_email_identity_feedback_attributes - [Link](https://github.com/upbound/provider-aws/actions/runs/4221841023/jobs/7329621704)
aws_sesv2_email_identity_mail_from_attributes - [Link](https://github.com/upbound/provider-aws/actions/runs/4221845022/jobs/7329630525)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/sesv2/configurationset.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/sesv2/configurationseteventdestination.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/sesv2/dedicatedippool.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/sesv2/emailidentity.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/sesv2/emailidentitymailfromattributes.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Pull request merged**
