### PR TITLE
Moving lightsail (6) resources to v1beta version

### LINKED ISSUE #300: Moving lightsail (6) resources to v1beta version
Moving 6 resources in the lightsail group:

- [x] [aws_lightsail_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_domain)
- [x] [aws_lightsail_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance)
- [x] [aws_lightsail_instance_public_ports](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance_public_ports)
- [x] [aws_lightsail_key_pair](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_key_pair)
- [x] [aws_lightsail_static_ip](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_static_ip)
- [x] [aws_lightsail_static_ip_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_static_ip_attachment)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
Adding new resources from group lightsail:
- [x] [aws_lightsail_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_domain)
- [x] [aws_lightsail_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance)
- [x] [aws_lightsail_instance_public_ports](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance_public_ports)
- [x] [aws_lightsail_key_pair](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_key_pair)
- [x] [aws_lightsail_static_ip](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_static_ip)
- [x] [aws_lightsail_static_ip_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_static_ip_attachment)

Fixes #300 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_lightsail_instance` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3734776930/jobs/6337241112)
`aws_lightsail_domain` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3734761942/jobs/6337207092)
`aws_lightsail_instance_public_ports` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3734747618/jobs/6337175235)
`aws_lightsail_key_pair` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3734735149/jobs/6337146653)
`aws_lightsail_static_ip` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3734698477/jobs/6337062280)
`aws_lightsail_static_ip_attachment` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3734647607/jobs/6336949153)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/domain.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/instance.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/instancepublicports.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/keypair.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/staticip.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/staticipattachment.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/staticipattachment.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/staticip.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/keypair.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/instancepublicports.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/lightsail/domain.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Pull request merged**
