### PR TITLE
Moving macie2 (6) resources to v1beta1 version

### LINKED ISSUE #308: Moving macie2 (6) resources to v1beta1 version
Moving 6 resources in the macie2 group:

- [x] [aws_macie2_account](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_account)
- [x] [aws_macie2_classification_job](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_classification_job)
- [x] [aws_macie2_custom_data_identifier](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_custom_data_identifier)
- [x] [aws_macie2_findings_filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_findings_filter)
- [x] [aws_macie2_invitation_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_invitation_accepter)
- [x] [aws_macie2_member](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_member)

### PR DESCRIPTION
**Pull request by steperchuk**
### Description of your changes
Moving 6 resources in the macie2 group:

- [x] [aws_macie2_account](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_account)
- [x] [aws_macie2_classification_job](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_classification_job)
- [x] [aws_macie2_custom_data_identifier](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_custom_data_identifier)
- [x] [aws_macie2_findings_filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_findings_filter)
- [x] [aws_macie2_invitation_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_invitation_accepter)
- [x] [aws_macie2_member](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_member)

Fixes #308

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually and Uptest
[aws_macie2_account](https://github.com/upbound/provider-aws/actions/runs/3740530193)
[aws_macie2_classification_job](https://github.com/upbound/provider-aws/actions/runs/3741287819)
[aws_macie2_custom_data_identifier](https://github.com/upbound/provider-aws/actions/runs/3741183628)
[aws_macie2_findings_filter](https://github.com/upbound/provider-aws/actions/runs/3741103967)
[aws_macie2_invitation_accepter](https://github.com/upbound/provider-aws/actions/runs/3741007314)
[aws_macie2_member](https://github.com/upbound/provider-aws/actions/runs/3740902618)

### CODE REVIEW

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/account.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/classificationjob.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/customdataidentifier.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/invitationaccepter.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/member.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/member.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/invitationaccepter.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/findingsfilter.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/customdataidentifier.yaml"

**Comment by steperchuk** [comment]
/test-examples="examples/macie2/classificationjob.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @steperchuk LGTM!

**Pull request merged**
