### PR TITLE
Bump Terraform provider version to v4.56.0

### LINKED ISSUE #575: Upgrade to the latest upstream Terraform provider
We need to update the upstream Terraform provider to the latest version.

See the previous PR here: https://github.com/upbound/provider-aws/pull/469

### PR DESCRIPTION
**Pull request by dverveiko**
### Description of your changes
Bumps Terraform provider version to `v4.56.0`

Fixes #575 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Uptests:
examples/appflow/flow.yaml -> https://github.com/upbound/provider-aws/actions/runs/4303131663
examples/sagemaker/userprofile.yaml -> https://github.com/upbound/provider-aws/actions/runs/4304439699

Manual tests for breaking API changes:

  - autoscaling.aws.upbound.io_policies.yaml
    
Screenshot 2023-03-01 at 13 45 33

  - examples/ecs/service.yaml -> There is a bug with constant update of Service resource. #585 
 
Screenshot 2023-03-01 at 15 50 50

### CODE REVIEW

**Comment by dverveiko** [comment]
/test-examples="examples/appflow/flow.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/ecs/service.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/sagemaker/userprofile.yaml"

**Comment by dverveiko** [comment]
/test-examples="examples/ecs/service.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @dverveiko LGTM!

**Pull request merged**
