### PR TITLE
Adding  aws_redshift_cluster, aws_redshift_event_subscription, aws_redshift_parameter_group, aws_redshift_scheduled_action, aws_redshift_snapshot_schedule, aws_redshift_snapshot_schedule_association, aws_redshift_subnet_groupto v1beta1

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Adding 7 resources:

- [x] [aws_redshift_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster)
- [x] [aws_redshift_event_subscription](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_event_subscription)
- [x] [aws_redshift_parameter_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_parameter_group)
- [x] [aws_redshift_scheduled_action](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_scheduled_action)
- [x] [aws_redshift_snapshot_schedule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_snapshot_schedule)
- [x] [aws_redshift_snapshot_schedule_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_snapshot_schedule_association)
- [x] [aws_redshift_subnet_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_subnet_group)

Fixes https://github.com/upbound/provider-aws/issues/318

I have:

- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually
Uptest:
 aws_redshift_cluster - https://github.com/upbound/provider-aws/actions/runs/3799475875
 aws_redshift_event_subscription - https://github.com/upbound/provider-aws/actions/runs/3799664601
 aws_redshift_parameter_group - https://github.com/upbound/provider-aws/actions/runs/3799488111
 aws_redshift_scheduled_action - https://github.com/upbound/provider-aws/actions/runs/3799805247
 aws_redshift_snapshot_schedule - https://github.com/upbound/provider-aws/actions/runs/3799497081
 aws_redshift_snapshot_schedule_association - https://github.com/upbound/provider-aws/actions/runs/3799884506
 aws_redshift_subnet_group - https://github.com/upbound/provider-aws/actions/runs/3799503049

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/cluster.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/parametergroup.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/snapshotschedule.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/subnetgroup.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/eventsubscription.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/scheduledaction.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/snapshotcopygrant.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/snapshotscheduleassociation.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/snapshotcopygrant.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/redshift/snapshotcopygrant.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
