### PR TITLE
DO NOT MERGE: Test Uptest

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

Fixes #

I have:

- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Comment by sergenyalcin** [comment]
/test-examples="examples/timestreamwrite/database.yaml,examples/wafregional/bytematchset.yaml,examples/kinesis/streamconsumer.yaml,examples/kinesisvideo/stream.yaml,examples/pinpoint/app.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/chime/voiceconnector.yaml,examples/licensemanager/licenseconfiguration.yaml,examples/ssm/patchbaseline.yaml,examples/signer/signingprofile.yaml,examples/servicecatalog/portfolio.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/lakeformation/resource.yaml,examples/secretsmanager/secretpolicy.yaml,examples/kms/externalkey.yaml,examples/quicksight/group.yaml,examples/elastictranscoder/preset.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/wafregional/bytematchset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/wafregional/bytematchset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/streamconsumer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisvideo/stream.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/pinpoint/app.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/wafregional/bytematchset.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/streamconsumer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesisvideo/stream.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/pinpoint/app.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/kinesis/stream.yaml,examples/kinesis/streamconsumer.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/appstream/stack.yaml"

**Comment by sergenyalcin** [comment]
/test-examples="examples/ec2/serialconsoleaccess.yaml"

**Pull request closed without merging**
