### PR TITLE
Configure qldb group and add examples

### PR DESCRIPTION
**Pull request by turkenf**
### Description of your changes

This PR configures resources in the qldb group:

- [aws_qldb_ledger](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/qldb_ledger)
- [aws_qldb_stream](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/qldb_stream)

Fixes: https://github.com/upbound/provider-aws/issues/316

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- `aws_qldb_ledger`, M, U(https://github.com/upbound/provider-aws/actions/runs/3759433906)
```shell
NAME                                       READY   SYNCED   EXTERNAL-NAME   AGE
ledger.qldb.aws.upbound.io/sample-ledger   True    True     sample-ledger   10m
```
- `aws_qldb_stream` M, U(https://github.com/upbound/provider-aws/actions/runs/3766204149)
```shell
NAME                                           READY   SYNCED   EXTERNAL-NAME        AGE
policy.iam.aws.upbound.io/sample-user-policy   True    True     sample-user-policy   8m58s

NAME                                  READY   SYNCED   EXTERNAL-NAME   AGE
role.iam.aws.upbound.io/sample-role   True    True     sample-role     8m58s

NAME                                                               READY   SYNCED   EXTERNAL-NAME                            AGE
rolepolicyattachment.iam.aws.upbound.io/sample-policy-attachment   True    True     sample-role-20221222132508416400000001   8m5
8s

NAME                                    READY   SYNCED   EXTERNAL-NAME   AGE
stream.kinesis.aws.upbound.io/example   True    True     example         8m58s

NAME                                       READY   SYNCED   EXTERNAL-NAME   AGE
ledger.qldb.aws.upbound.io/sample-ledger   True    True     sample-ledger   8m58s

NAME                                 READY   SYNCED   EXTERNAL-NAME            AGE
stream.qldb.aws.upbound.io/example   True    True     42BHIjOjhHbD8FeL3sErdi   8m58s
```

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/qldb/ledger.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/qldb/stream.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/qldb/stream.yaml"

**Comment by turkenf** [comment]
This PR is ready for review.

**Review by sergenyalcin — APPROVED** [review]
Thanks @turkenf LGTM!

**Pull request merged**
