### PR TITLE
Adding elbv2 (1) resource to v1beta1 version

### LINKED ISSUE #293: Moving elbv2 (1) resource to v1beta1 version
Moving 1 resource in the elbv2 group:

- [x] [aws_lb_listener_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Add 1 resource in the elbv2 group:

- [x] [aws_lb_listener_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule)

Fixes #293 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`aws_lb_listener_rule` manually and uptest - https://github.com/upbound/provider-aws/actions/runs/3760513664

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/elbv2/lblistenerrule.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/elbv2/lblistenerrule.yaml"

**Review by sergenyalcin — COMMENTED** [review]
We may consider to run the Uptest for the resources that has some changes in their example manifests. Because we need to be sure that these examples are working properly.

**Comment by mykolalosev** [comment]
/test-examples="examples/elbv2/lblistenerrule.yaml"

**Comment by mykolalosev** [comment]
@sergenyalcin hello. I have changed the PR to match the affected resources to the scope of the issue.
Also I want to mention that the `LBTargetGroup` resource is provided as a single file too, however I didn't attach an auto-generated file of this resource to the PR by the same reason - out of scope. Of course in the main resource it persists.
Thank you!

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
