### PR TITLE
Moving memorydb (5) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Moving 5 resources in the memorydb group:

- [x] [aws_memorydb_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_acl)
- [x] [aws_memorydb_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_cluster)
- [x] [aws_memorydb_parameter_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_parameter_group)
- [x] [aws_memorydb_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_snapshot)
- [x] [aws_memorydb_subnet_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_subnet_group)

Fixes https://github.com/upbound/provider-aws/issues/312

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually

Uptests:
[aws_memorydb_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_acl) - https://github.com/upbound/provider-aws/actions/runs/3764468254/jobs/6398932348
[aws_memorydb_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_cluster) - https://github.com/upbound/provider-aws/actions/runs/3764477956/jobs/6398951098
[aws_memorydb_parameter_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_parameter_group) - https://github.com/upbound/provider-aws/actions/runs/3764478930/jobs/6398953073
[aws_memorydb_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_snapshot) - https://github.com/upbound/provider-aws/actions/runs/3764479689/jobs/6398954696
[aws_memorydb_subnet_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_subnet_group) - https://github.com/upbound/provider-aws/actions/runs/3765422777/jobs/6400885215

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/memorydb/acl.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/memorydb/cluster.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/memorydb/parametergroup.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/memorydb/snapshot.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/memorydb/subnetgroup.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/memorydb/subnetgroup.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @svscheg LGTM!

**Pull request merged**
