### PR TITLE
Adding aws_codepipeline_custom_action_type, aws_cognito_risk_configuration, aws_connect_instance_storage_config, aws_connect_phone_number, aws_connect_user, aws_connect_vocabulary resources to v1beta1 version

### LINKED ISSUE #492: Moving codepipeline(1), cognito(1), connect(4) resources to v1beta1 version
* `codepipeline`
  * [x] [aws_codepipeline_custom_action_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline_custom_action_type)

* `cognito`
  * [x] [aws_cognito_risk_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_risk_configuration)

* `connect`
  * [x] [aws_connect_instance_storage_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_instance_storage_config)
  * [x] [aws_connect_phone_number](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_phone_number)
  * [x] [aws_connect_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_user)
  * [x] [aws_connect_vocabulary](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_vocabulary)

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Adding 6 resources to v1beta1:
* `codepipeline`
  * [x] [aws_codepipeline_custom_action_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline_custom_action_type)

* `cognito`
  * [x] [aws_cognito_risk_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_risk_configuration)

* `connect`
  * [x] [aws_connect_instance_storage_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_instance_storage_config)
  * [x] [aws_connect_phone_number](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_phone_number)
  * [x] [aws_connect_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_user)
  * [x] [aws_connect_vocabulary](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_vocabulary)

Fixes #492 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual:
aws_connect_user - Requires at least one SecurityProfile security_profile_id
aws_connect_user

Manual & Uptest:
aws_codepipeline_custom_action_type - https://github.com/upbound/provider-aws/actions/runs/4187983976
aws_cognito_risk_configuration - https://github.com/upbound/provider-aws/actions/runs/4187986242
aws_connect_instance_storage_config - https://github.com/upbound/provider-aws/actions/runs/4187988683
aws_connect_phone_number - https://github.com/upbound/provider-aws/actions/runs/4187991380
aws_connect_vocabulary - https://github.com/upbound/provider-aws/actions/runs/4187994325

### CODE REVIEW

**Comment by mykolalosev** [comment]
/test-examples="examples/codepipeline/customactiontype.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/cognitoidp/riskconfiguration.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/connect/instancestorageconfig.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/connect/phonenumber.yaml"

**Comment by mykolalosev** [comment]
/test-examples="examples/connect/vocabulary.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
