### PR TITLE
Function type config.ConfigurationInjector now returns an error

### PR DESCRIPTION
**Pull request by ulucinar**
### Description of your changes

Depends on: https://github.com/crossplane/upjet/pull/344

There's a breaking change in https://github.com/crossplane/upjet/pull/344 and [`config.ConfigurationInjector`](https://github.com/crossplane/upjet/blob/f6a1a0de74519634fd9e53d4f42cf7ee32fcd05e/pkg/config/resource.go#L515) now returns an error. This PR updates the usages of the old API.

This PR also bumps the uptest version to `v0.11.0` and adds the `uptest.upbound.io/disable-import: "true"` annotation to the example manifest `examples/s3/v1beta1/object.yaml`. Please see this [comment](https://github.com/upbound/provider-aws/pull/1150#issuecomment-1944141876).

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Via the following uptest runs:
- https://github.com/upbound/provider-aws/actions/runs/7905023715
- https://github.com/upbound/provider-aws/actions/runs/7905068938
- https://github.com/upbound/provider-aws/actions/runs/7905281277

### CODE REVIEW

**Comment by ulucinar** [comment]
/test-examples="examples/s3/v1beta1/object.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @ulucinar LGTM!

**Comment by ulucinar** [comment]
Looks like we've hit [this](https://github.com/upbound/provider-aws/issues/978) issue with the `Object.s3` uptest run.

**Comment by ulucinar** [comment]
/test-examples="examples/s3/v1beta1/object.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/s3/v1beta1/object.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/s3/v1beta1/bucket.yaml"

**Comment by ulucinar** [comment]
/test-examples="examples/ec2/v1beta1/securitygrouprule-self-true.yaml"

**Pull request merged**
