### PR TITLE
Moving swf(1), timestreamwrite(2) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Moving `swf` (1) resources to v1beta1 version
- [x] [`aws_swf_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/swf_domain)

Moving `timestreamwrite` (2) resources to v1beta1 version
- [x] [`aws_timestreamwrite_database`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_database)
- [x] [`aws_timestreamwrite_table`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_table)

Fixes https://github.com/upbound/provider-aws/issues/377

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually

Uptests:

[`aws_swf_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/swf_domain) - https://github.com/upbound/provider-aws/actions/runs/3806314468/jobs/6474999621

[`aws_timestreamwrite_database`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_database) - https://github.com/upbound/provider-aws/actions/runs/3806315368/jobs/6475000962
[`aws_timestreamwrite_table`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_table) - https://github.com/upbound/provider-aws/actions/runs/3806316327/jobs/6475002802

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/swf/domain.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/timestreamwrite/database.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/timestreamwrite/table.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @svscheg LGTM!

**Pull request merged**
