### PR TITLE
Moving fsx (4) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
### Description of your changes
Moving 4 resources in the fsx group:

- [x] [aws_fsx_backup](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_backup)
- [x] [aws_fsx_data_repository_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_data_repository_association)
- [x] [aws_fsx_lustre_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_lustre_file_system)
- [x] [aws_fsx_windows_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_windows_file_system)

Fixes https://github.com/upbound/provider-aws/issues/297

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually

Uptests:
[aws_fsx_windows_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_windows_file_system) - https://github.com/upbound/provider-aws/actions/runs/3758357604/jobs/6386606496

[aws_fsx_lustre_file_system](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_lustre_file_system) - https://github.com/upbound/provider-aws/actions/runs/3760353927

[aws_fsx_backup](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_backup) - https://github.com/upbound/provider-aws/actions/runs/3760558525/jobs/6391404068

[aws_fsx_data_repository_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_data_repository_association) - https://github.com/upbound/provider-aws/actions/runs/3761504295/jobs/6393326400

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/fsx/windowsfilesystem.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/fsx/datarepositoryassociation.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/fsx/lustrefilesystem.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/fsx/backup.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/fsx/datarepositoryassociation.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/fsx/datarepositoryassociation.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @svscheg LGTM!

**Pull request merged**
