### PR TITLE
Moving route53recoveryreadiness (2),s3control (3) resources to v1beta1 version

### PR DESCRIPTION
**Pull request by svscheg**
add resources

### Description of your changes
External name configuration of 2 resources in the `route53recoveryreadiness` group:
- [x] [`aws_route53recoveryreadiness_recovery_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoveryreadiness_recovery_group)
- [x] [`aws_route53recoveryreadiness_resource_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoveryreadiness_resource_set)

External name configuration of 3 resources in the `s3control` group:
- [x] [`aws_s3_access_point`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_access_point)
- [x] [`aws_s3_account_public_access_block`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_account_public_access_block)
- [x] [`aws_s3control_access_point_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_access_point_policy)

Fixes https://github.com/upbound/provider-aws/issues/50

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manually

Uptests:
External name configuration of 2 resources in the `route53recoveryreadiness` group:
[`aws_route53recoveryreadiness_recovery_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoveryreadiness_recovery_group) - https://github.com/upbound/provider-aws/actions/runs/3712703457/jobs/6294526350
[`aws_route53recoveryreadiness_resource_set`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53recoveryreadiness_resource_set) - https://github.com/upbound/provider-aws/actions/runs/3712704635/jobs/6294528997

External name configuration of 3 resources in the `s3control` group:
[`aws_s3_access_point`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_access_point) - https://github.com/upbound/provider-aws/actions/runs/3712706588/jobs/6294533146
[`aws_s3_account_public_access_block`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_account_public_access_block) - https://github.com/upbound/provider-aws/actions/runs/3712717328/jobs/6294555999
[`aws_s3control_access_point_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_access_point_policy) - https://github.com/upbound/provider-aws/actions/runs/3712829716/jobs/6294794487

### CODE REVIEW

**Comment by svscheg** [comment]
/test-examples="examples/route53recoveryreadiness/recoverygroup.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/route53recoveryreadiness/resourceset.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/accesspoint.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/accesspointpolicy.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/accountpublicaccessblock.yaml"

**Comment by svscheg** [comment]
/test-examples="examples/s3control/accesspointpolicy.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @svscheg LGTM!

**Pull request merged**
