### PR TITLE
Adding aws_redshift_snapshot_copy_grant to v1beta1 version

### LINKED ISSUE #407: Moving redshift (1) resources to v1beta1 version
Moving 1 resource in the redshift group:

- [x] [aws_redshift_snapshot_copy_grant](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_snapshot_copy_grant)

Extracted from https://github.com/upbound/provider-aws/issues/318

### PR DESCRIPTION
**Pull request by mykolalosev**
### Description of your changes
Adding 1 resource in the redshift group:

- [x] [aws_redshift_snapshot_copy_grant](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_snapshot_copy_grant)

Fixes #407 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Manual:
aws_redshift_snapshot_copy_grant - can't run uptest because of receive an error "Resource aws_redshift_snapshot_copy_grant.test has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed."

aws_redshift_snapshot_copy_grant

### CODE REVIEW

**Comment by mykolalosev** [comment]
I haven't added an `upjet.upbound.io/manual-intervention` annotation because of this resource successfully applying and deleting, @sergenyalcin is it ok?

**Comment by sergenyalcin** [comment]
> I haven't added an `upjet.upbound.io/manual-intervention` annotation because of this resource successfully applying and deleting, @sergenyalcin is it ok?

Did you observe that provisioning and deletion of this resource were successfully completed in manual tests? If it is the case we can do this

**Comment by mykolalosev** [comment]
> > I haven't added an `upjet.upbound.io/manual-intervention` annotation because of this resource successfully applying and deleting, @sergenyalcin is it ok?
> 
> Did you observe that provisioning and deletion of this resource were successfully completed in manual tests? If it is the case we can do this

Yes, manually I've created and deleted the resource successfully.

**Review by sergenyalcin — APPROVED** [review]
Thanks @mykolalosev LGTM!

**Pull request merged**
