### PR TITLE
Moving schemas (3) resources to v1beta1 version

### LINKED ISSUE #322: Moving schemas (3) resources to v1beta1 version
Moving 3 resources in the schemas group:

- [ ] [aws_schemas_discoverer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_discoverer)
- [ ] [aws_schemas_registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_registry)
- [ ] [aws_schemas_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_schema)

### PR DESCRIPTION
**Pull request by MyzaTaras**
### Description of your changes
Adding new resources from group schemas:

- [x] [aws_schemas_discoverer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_discoverer)
- [x] [aws_schemas_registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_registry)
- [x] [aws_schemas_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_schema)

Fixes #322

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

`aws_schemas_discoverer ` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3739263707/jobs/6346264617)
`aws_schemas_registry ` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3739266269/jobs/6346271929)
`aws_schemas_schema ` - manually and [uptest](https://github.com/upbound/provider-aws/actions/runs/3739269835/jobs/6346277204)

### CODE REVIEW

**Comment by MyzaTaras** [comment]
/test-examples="examples/schemas/discoverer.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/schemas/registry.yaml"

**Comment by MyzaTaras** [comment]
/test-examples="examples/schemas/schema.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @MyzaTaras LGTM!

**Comment by MyzaTaras** [comment]
Fixed marge conflict in "externalname.go" file.

**Pull request merged**
