### PR TITLE
elbv2: add aws_lb_listener_certificate to v1beta1

### LINKED ISSUE #338: Moving elbv2 (1) resource to v1beta1 version
Moving 1 resource in the elbv2 group:

- [ ] [aws_lb_listener_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_certificate)

While testing the resource was figured out impossibility of applying it by the reason of requires an acm-certificate which requires provisioned domain. As a possible workaround was suggested a manual generating a certificate and importing it as an acm-certificate.

Received eror:
```
error adding LB Listener Certificate: UnsupportedCertificate: The certificate 'arn:aws:acm:us-west-1:153891904029:certificate/350a08d7-e86f-4180-91fc-e63dcdb8e592' must have a fully-qualified domain name, a supported signature, and a supported key size.
```

Extracted from: https://github.com/upbound/provider-aws/issues/293

### PR DESCRIPTION
**Pull request by phyrog**
<!--
Thank you for helping to improve Official AWS Provider!

Please read through https://git.io/fj2m9 if this is your first time opening a
Official AWS Provider pull request. Find us in https://slack.crossplane.io/messages/dev if
you need any help contributing.
-->

### Description of your changes

<!--
Briefly describe what this pull request does. Be sure to direct your reviewers'
attention to anything that needs special consideration.

We love pull requests that resolve an open Official AWS Provider issue. If yours does, you
can uncomment the below line to indicate which issue your PR fixes, for example
"Fixes #500":

-->
Fixes #338 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

<!--
Before reviewers can be confident in the correctness of this pull request, it
needs to tested and shown to be correct. Briefly describe the testing that has
already been done or which is planned for this change.
-->

Manually:

#### Prerequisites

- An existing public DNS zone under your control (e.g. Route53 public zone)
- A valid Certificate within Certificate Manager (we will need the ARN) as the default listener certificate

#### Modifications to the example manifests

- Set the `certificateArn` field in the `LBListener` resource to the ARN of your existing certificate
- Update the `domainName` field in the `Certificate` reosurce to a valid domain name under your existing public zone

#### Apply the manifests

- The `Certificate` resource will not complete until you create the necessary domain records for validation.
  - For Route53: Open the Certificate Manager console, click on the newly created certificate and click the `Create records in Route 53` button
  - When validation completes, the `Certificate` resource will become `Ready` and the rest of the resources will be soon after as well

```
NAME                                                 READY   SYNCED   EXTERNAL-NAME                                                                                                                                                                                                             AGE
lblistenercertificate.elbv2.aws.upbound.io/example   True    True     arn:aws:elasticloadbalancing:us-west-1:xxxxxxxxxxxx:listener/app/tf-lb-2023112810522523740000000a/d74830cac6d6b8c0/cf39c672de841882_arn:aws:acm:us-west-1:xxxxxxxxxxxx:certificate/4bb1f2cf-8d11-4a51-8549-0364827ed50a   10s

NAME                                     READY   SYNCED   EXTERNAL-NAME                                                                         AGE
certificate.acm.aws.upbound.io/example   True    True     arn:aws:acm:us-west-1:xxxxxxxxxxxx:certificate/4bb1f2cf-8d11-4a51-8549-0364827ed50a   87s

NAME                                      READY   SYNCED   EXTERNAL-NAME                                                                                                                         AGE
lblistener.elbv2.aws.upbound.io/example   True    True     arn:aws:elasticloadbalancing:us-west-1:xxxxxxxxxxxx:listener/app/tf-lb-2023112810522523740000000a/d74830cac6d6b8c0/cf39c672de841882   7m14s

NAME                              READY   SYNCED   EXTERNAL-NAME                                                                                                            AGE
lb.elbv2.aws.upbound.io/example   True    True     arn:aws:elasticloadbalancing:us-west-1:xxxxxxxxxxxx:loadbalancer/app/tf-lb-2023112810522523740000000a/d74830cac6d6b8c0   10m

NAME                               READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/elbv2-vpc   True    True     vpc-0ab86a8e1b9c1bbd6   31m

NAME                                                        READY   SYNCED   EXTERNAL-NAME           AGE
internetgateway.ec2.aws.upbound.io/elbv2-internet-gateway   True    True     igw-06bc229a1e9d16389   31m

NAME                                       READY   SYNCED   EXTERNAL-NAME              AGE
subnet.ec2.aws.upbound.io/elbv2-subnet     True    True     subnet-0b635785fa9ba0507   31m
subnet.ec2.aws.upbound.io/elbv2-subnet-2   True    True     subnet-0dc539fa12f90c3ef   31m

NAME                                                   READY   SYNCED   EXTERNAL-NAME          AGE
securitygroup.ec2.aws.upbound.io/elbv2-securitygroup   True    True     sg-0affbb0dbf030cace   31m
```

### CODE REVIEW

**Comment by turkenf** [comment]
/test-examples="examples/elbv2/lblistenercertificate.yaml"

**Comment by phyrog** [comment]
/test-examples="examples/elbv2/lblistenercertificate.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/elbv2/lblistenercertificate.yaml"

**Review by turkenf — COMMENTED** [review]
Thank you for your efforts on this PR @phyrog, I left a few comments for you to consider.

Additionally, since this resource requires manual intervention, we cannot verify it with automatic testing. For this, can you fill in the "How has this code been tested" section stating that you tested the resource like [here](https://github.com/upbound/provider-aws/pull/617#issue-1633909218)?

**Comment by phyrog** [comment]
@turkenf Fixed all of your review comments and added the manual test description to the PR description.

**Review by turkenf — APPROVED** [review]
Many thanks for your contribution @phyrog, LGTM.

**Pull request merged**
